### ISSUE TITLE
After login get 401 on getting UserInfo, i need to reload the page to get it OK

### ISSUE THREAD

**Issue by BillelMessaadi** [AxaFrance/oidc-client#1000]
### Issue and Steps to Reproduce

After login get 401 on getting UserInfo, i need to reload the page to get it OK or to force the render.
I am using react app and Keycloak as OIDC Server
### Versions
6.15.19
### Screenshots
![image](https://user-images.githubusercontent.com/9382324/225837591-c261e9dd-a004-47f5-9517-8a109a3d5311.png)

![image](https://user-images.githubusercontent.com/9382324/225836976-dc9fedb8-deaa-40a6-ab13-004d781da1b7.png)

#### Expected
Get user info directly after login
#### Actual
I get null object
### Additional Details
In the userinfo request we can see that the token is not valid, seems to be not injected
- Installed packages:
@axa-fr/react-oidc

**Comment by guillaume-chervet** [comment]
Hi @BillelMessaadi , thankbyou for your issue.
Dibyou have a sample ofbyour configuration?

**Comment by BillelMessaadi** [comment]
const configuration = {
    client_id: "[client-id],
    redirect_uri: window.location.origin + "/authentication/callback",
    silent_redirect_uri:
      window.location.origin + "/authentication/silent-callback",
    scope: "openid profile address email phone", // offline_access scope allow your client to retrieve the refresh_token
    authority: "http://localhost:8080/realms/[realm-name]",
    refresh_time_before_tokens_expiration_in_second: 40,
    service_worker_relative_url: "/OidcServiceWorker.js",
    service_worker_only: true,
    token_renew_mode: TokenRenewMode.access_token_invalid,
  };

**Comment by BillelMessaadi** [comment]
I also have the same issue using the demo app

**Comment by guillaume-chervet** [comment]
thank you @BillelMessaadi .

May you check in the network tab if in your failing request. Access token is injected in theAuthorization http header?

**Comment by BillelMessaadi** [comment]
<img width="812" alt="image" src="https://user-images.githubusercontent.com/9382324/225940148-fb81d5db-b569-41c5-a93b-3dd60334d2d3.png">

**Comment by guillaume-chervet** [comment]
Hi @BillelMessaadi it look like you service worker is not active for this request. Are you testing with debugging tool activated and cache disabled? It can bring this strange behavior.

**Comment by guillaume-chervet** [comment]
Hi @BillelMessaadi , do you have any news? Did you solve your issue?

**Comment by guillaume-chervet** [comment]
hi @BillelMessaadi , I close the issue. Thank you for it. Feel free to reopen it if needed.
