### ISSUE TITLE
Release v6.16.8 doesn't copy service worker in public directory anymore

### ISSUE THREAD

**Issue by AnimaLupi** [AxaFrance/oidc-client#1016]
### Issue and Steps to Reproduce

`npm install  @axa-fr/react-oidc@6.16.8`

The file `OdicServiceWorker.js` isn't copied to the `public` directory (but previous version is removed).

### Versions
6.16.8

#### Expected
The service worker is installed, updated or preserved

#### Actual
The service worker is removed

The problem isn't present in version 6.16.7.

**Comment by AnimaLupi** [comment]
Thank you for the fast feedback!

Yes, I'm using create react app with `react-scripts` at version 4.0.3 and some (minimal) customization with `craco` (`craco-plugin-env`, `craco-less`).

If you think that could be the cause of the issue (or some other dev dependency used in the build chain) I can provide the full package.json and/or the craco configuration (which is limited to those two plugins, though).

**Comment by Zamaletdinov** [comment]
I experience the same issue at the moment with vite - migrated to it from CRA a long while ago

**Comment by NickCain** [comment]
I also have the same problem since upgrading, also it seems to not be fixed by rolling back for me either.

**Comment by Zamaletdinov** [comment]
@NickCain I have downgraded back to 6.15.5 and the file has been regenerated

**Comment by NickCain** [comment]
@Zamaletdinov Thanks for your reply. Unfortuately even that version doesnt generate it for me now, i've even removed all node_modules and yarn cache

**Comment by AnimaLupi** [comment]
Thank you for the fix, now updating the package preserve/updates the `OidcServiceWorker.js` file properly.

**Comment by guillaume-chervet** [comment]
Hi @AnimaLupi , may we close the issue?

**Comment by AnimaLupi** [comment]
> Hi @AnimaLupi , may we close the issue?

For what I'm experiencing now, it's fixed and can be closed, thank you! :+1:

**Comment by guillaume-chervet** [comment]
Thank you very much for your issue @AnimaLupi .
