### ISSUE TITLE
Automatic login of opened tabs

### ISSUE THREAD

**Issue by nicolas-goudry** [AxaFrance/oidc-client#1055]
### Issue and Steps to Reproduce

**This is not an issue but rather a question / feature request.**

I’m creating a front-end starter template for my company, with several things pre-configured, including the authentication system. I’m pretty happy with what I came up with, in great part thanks to `react-oidc` !
I tried implementing the auth system with `oidc-react` but it was too much hassle to work with, lots of configuration and custom code would be needed to be able to support the same features as `react-oidc`… So, first of all: thanks for this great library !

So far, the following features are working as I would expect them:
- users are automatically logged in on page load if they were previously logged in
- signing out from one tab effectively signs out all other tabs

However, I’d like to be able to automatically connect a user if they sign in from another tab, though I’m not even sure if this is possible and how I would achieve this.

I thought about an event mechanism, that would notify all tabs of a user signing in through local storage for example
and then would trigger a silent login. But that seems kind of hackish and, given the fact that `react-oidc` uses a service worker, maybe implementing this internally would be better ?

What are your thoughts about all this ? Thanks !

### Versions

6.19.0

**Comment by guillaume-chervet** [comment]
Hi @nicolas-goudry , thank you for your issue.

You can get want you want by using ServiceWorker mode or localStorage.
Default is sessionStorage link to the session.

You can increase user experience by using silentsign but it require openid server to be on the same domain than your web application.

**Comment by nicolas-goudry** [comment]
Thanks for your quick answer !

I’m using the Service Worker mode. I thought about using the `auth-callback` route to handle this, but in the end I used the `callbackSuccessComponent` to set a value in the local storage upon successful login. I created a specific component which renders `null` but also listen to storage events and force a page reload on successful login.

Overall: it works. But I’m not really fond of the force page reload… I can’t find any examples of silent sign in, how should I trigger it ?
Also, I guess it will work with `localhost`, but when deployed the openid server is on `auth.mydomain.com` and the applications are on `app-name.mydomain.com`, would silent sign in work in such a configuration ?

**Comment by nicolas-goudry** [comment]
Here is how it looks like:

https://github.com/AxaFrance/react-oidc/assets/8753998/ebab32eb-8141-416e-aace-46c351d4f125

The `AuthSuccess` component `useEffect`:

```tsx
useEffect(() => {
  // Notify other tabs of successful sign in
  window.localStorage.setItem('signIn', 'trigger')
  window.localStorage.removeItem('signIn')

  // Force redirect after 3s
  const redirectTimeout = setTimeout(() => {
    window.location.href = '/'
  }, 3000)

  return () => {
    clearTimeout(redirectTimeout)
  }
}, [])
```

The `AuthListener` component that reloads the page on sign in events (it needs to be a children of the `OidcProvider`):

```tsx
import { useOidc } from '@axa-fr/react-oidc'
import { useEffect } from 'react'

function AuthListener() {
  const { isAuthenticated } = useOidc()

  useEffect(() => {
    function onStorage(event: StorageEvent) {
      // Force reload page if not signed in and received sign in notification
      if (event.key === 'signIn' && event.newValue === 'trigger' && !isAuthenticated) {
        window.location.reload()
      }
    }

    window.addEventListener('storage', onStorage)

    return () => {
      window.removeEventListener('storage', onStorage)
    }
  }, [isAuthenticated])
  return null
}

export default AuthListener
```

**Comment by guillaume-chervet** [comment]
Hi @nicolas-goudry , thank you very mucv for this awesome feedback.

In the demo you have some examples of silent signin.

**Comment by nicolas-goudry** [comment]
Hi @guillaume-chervet, sorry for my late reply.

Actually I sent the whole video by mistake, only the first 8 seconds or so are relevant to my message… Sorry about that.

So, I think that what you are calling a « silent sign in » is happening around 0:05 in the video. If this is the case, this is a full page refresh… That’s what I’m trying to avoid: doing a full page refresh. Isn’t there a method to programmatically refresh the authentication state without reloading the page ?

**Comment by guillaume-chervet** [comment]
Hi @nicolas-goudry ,

You can do it. In the demo login from the first page, then go to multitab page. You will see SilentSigin button. You will be able to sign without any page refresh.

**Comment by nicolas-goudry** [comment]
Hi @guillaume-chervet, I missed that part of the demo. I’ll try to implement it in the same way. Thanks !

**Comment by guillaume-chervet** [comment]
hi @nicolas-goudry , did you succeded?

**Comment by nicolas-goudry** [comment]
Hi @guillaume-chervet, sorry for my delay. Sadly I didn’t have time to fully implement the auth mechanism like it’s done in the demo. I will have some time to work on that during August. I’ll let you know how it goes with full details ! Thanks for caring :slightly_smiling_face:

**Comment by nicolas-goudry** [comment]
Hi @guillaume-chervet I found some time to work on this but I wasn’t able to make it work… I gave you access to my repository if you would be kind enough to give it a look (`master` branch is with the full refresh code, `silent-login-no-refresh` branch is the closest that I could get to something working-ish). I can’t take my head around this, sometimes it works but I don’t get user info, sometimes it doesn’t work and the second tab just gets weird characters appended to the DOM.

I’ll stick with the full page refresh for now, which is in any case a better feature than what we already have (ie. no auto login sync between tabs)…

Also, it might not be the right place for talking about that, but if you ever happen to be around Paris I’ll gladly buy you a drink :slightly_smiling_face:

**Comment by nicolas-goudry** [comment]
Some updates here:

I managed to make the silent login work in a production-like environment using Docker.

But I still have two issues:

- I have an `auth-menu` component that looks like so:

```ts
function AuthMenu() {
  const { isAuthenticated, login, logout } = useOidc()
  const { oidcUser, oidcUserLoadingState } = useOidcUser()
  let renderAvatar = (): ReactNode | string => <Icon icon={faUser} />
  const handleSignIn = () => {
    login().then(noop).catch(noop)
  }

  const handleSignOut = () => {
    logout().then(noop).catch(noop)
  }

  if (oidcUserLoadingState === OidcUserStatus.Loading || oidcUserLoadingState === OidcUserStatus.LoadingError) {
    return null
  }

  if (isAuthenticated && oidcUser) {
    const matchInitials = oidcUser.name?.matchAll(/\b\w/g)

    if (matchInitials) {
      const initialsArray = [...matchInitials]

      renderAvatar = () => ((initialsArray.shift()?.[0] ?? '') + (initialsArray.pop()?.[0] ?? '')).toUpperCase()
    }
  }

  return (
    <div css={styles.auth}>
      {isAuthenticated && (<Dropdown>...</Dropdown>)}
      {!isAuthenticated && <Button onClick={handleSignIn}>Sign in</Button>}
    </div>
  )
}
```

When signing in in the production-like environment, this component renders correctly the user initials, but with the silent login feature, the `renderAvatar` is never overriden because `oidcUser` is falsy.

- in development, I have an issue which is related to Vite I think, which gives the following console output in the tab that does the silent signin process:

```
oidc:default:silentLoginAsync_begin {}
auth-provider.tsx:14 oidc:default:silentLoginAsync_begin {}
VM578 client:229 [vite] connecting...
VM588 client:229 [vite] connecting...
VM578 client:324 [vite] connected.
VM588 client:324 [vite] connected.
VM665 chunk-X3B7SAOS.js:377 [Violation] 'message' handler took 1701ms
VM665 chunk-X3B7SAOS.js:377 [Violation] 'message' handler took 1641ms
VM651 auth-provider.tsx:30 oidc:default:loginAsync_begin {}
VM672 auth-provider.tsx:30 oidc:default:loginAsync_begin {}
VM692 @axa-fr_react-oidc.js:380 TypeError: Failed to fetch
    at ue (VM708 @axa-fr_react-oidc.js:379:32)
    at Object.c [as startKeepAliveServiceWorker] (VM708 @axa-fr_react-oidc.js:441:37)
    at VM708 @axa-fr_react-oidc.js:826:129
VM708 @axa-fr_react-oidc.js:380 TypeError: Failed to fetch
    at ue (VM708 @axa-fr_react-oidc.js:379:32)
    at Object.c [as startKeepAliveServiceWorker] (VM708 @axa-fr_react-oidc.js:441:37)
    at VM708 @axa-fr_react-oidc.js:826:129
VM932 client:229 [vite] connecting...
VM934 client:229 [vite] connecting...
VM932 client:324 [vite] connected.
VM934 client:324 [vite] connected.
VM1010 auth-provider.tsx:30 oidc:default:loginCallbackAsync_begin {}
VM999 auth-provider.tsx:30 oidc:default:loginCallbackAsync_begin {}
VM1050 @axa-fr_react-oidc.js:888 Error: state not valid (expected: s8duP1PNc3RK5rnm, received: WiAfPEidbGw5p35v)
    at VM1050 @axa-fr_react-oidc.js:859:13
    at async t (VM1049 @axa-fr_react-oidc.js:1109:17)
(anonymous) @ VM1050 @axa-fr_react-oidc.js:888
await in (anonymous) (async)
t @ VM1050 @axa-fr_react-oidc.js:1109
loginCallbackAsync @ VM1050 @axa-fr_react-oidc.js:1112
silentLoginCallbackAsync @ VM1050 @axa-fr_react-oidc.js:1023
silentLoginCallbackAsync @ VM1050 @axa-fr_react-oidc.js:1276
(anonymous) @ VM1050 @axa-fr_react-oidc.js:1971
(anonymous) @ VM1050 @axa-fr_react-oidc.js:1972
commitHookEffectListMount @ VM987 chunk-X3B7SAOS.js:16904
commitPassiveMountOnFiber @ VM987 chunk-X3B7SAOS.js:18152
commitPassiveMountEffects_complete @ VM987 chunk-X3B7SAOS.js:18125
commitPassiveMountEffects_begin @ VM987 chunk-X3B7SAOS.js:18115
commitPassiveMountEffects @ VM987 chunk-X3B7SAOS.js:18105
flushPassiveEffectsImpl @ VM987 chunk-X3B7SAOS.js:19486
flushPassiveEffects @ VM987 chunk-X3B7SAOS.js:19443
(anonymous) @ VM987 chunk-X3B7SAOS.js:19324
workLoop @ VM987 chunk-X3B7SAOS.js:197
flushWork @ VM987 chunk-X3B7SAOS.js:176
performWorkUntilDeadline @ VM987 chunk-X3B7SAOS.js:384
Show 18 more frames
Show less
VM1010 auth-provider.tsx:30 oidc:default:loginCallbackAsync_error Error: state not valid (expected: s8duP1PNc3RK5rnm, received: WiAfPEidbGw5p35v)
    at VM1050 @axa-fr_react-oidc.js:859:13
    at async t (VM1049 @axa-fr_react-oidc.js:1109:17)
VM1050 @axa-fr_react-oidc.js:1025 Error: state not valid (expected: s8duP1PNc3RK5rnm, received: WiAfPEidbGw5p35v)
    at VM1050 @axa-fr_react-oidc.js:859:13
    at async t (VM1049 @axa-fr_react-oidc.js:1109:17)
silentLoginCallbackAsync @ VM1050 @axa-fr_react-oidc.js:1025
await in silentLoginCallbackAsync (async)
silentLoginCallbackAsync @ VM1050 @axa-fr_react-oidc.js:1276
(anonymous) @ VM1050 @axa-fr_react-oidc.js:1971
(anonymous) @ VM1050 @axa-fr_react-oidc.js:1972
commitHookEffectListMount @ VM987 chunk-X3B7SAOS.js:16904
invokePassiveEffectMountInDEV @ VM987 chunk-X3B7SAOS.js:18320
invokeEffectsInDev @ VM987 chunk-X3B7SAOS.js:19697
commitDoubleInvokeEffectsInDEV @ VM987 chunk-X3B7SAOS.js:19682
flushPassiveEffectsImpl @ VM987 chunk-X3B7SAOS.js:19499
flushPassiveEffects @ VM987 chunk-X3B7SAOS.js:19443
(anonymous) @ VM987 chunk-X3B7SAOS.js:19324
workLoop @ VM987 chunk-X3B7SAOS.js:197
flushWork @ VM987 chunk-X3B7SAOS.js:176
performWorkUntilDeadline @ VM987 chunk-X3B7SAOS.js:384
Show 14 more frames
Show less
VM1050 @axa-fr_react-oidc.js:1025 Error: state not valid (expected: s8duP1PNc3RK5rnm, received: WiAfPEidbGw5p35v)
    at VM1050 @axa-fr_react-oidc.js:859:13
    at async t (VM1049 @axa-fr_react-oidc.js:1109:17)
silentLoginCallbackAsync @ VM1050 @axa-fr_react-oidc.js:1025
await in silentLoginCallbackAsync (async)
silentLoginCallbackAsync @ VM1050 @axa-fr_react-oidc.js:1276
(anonymous) @ VM1050 @axa-fr_react-oidc.js:1971
(anonymous) @ VM1050 @axa-fr_react-oidc.js:1972
commitHookEffectListMount @ VM987 chunk-X3B7SAOS.js:16904
commitPassiveMountOnFiber @ VM987 chunk-X3B7SAOS.js:18152
commitPassiveMountEffects_complete @ VM987 chunk-X3B7SAOS.js:18125
commitPassiveMountEffects_begin @ VM987 chunk-X3B7SAOS.js:18115
commitPassiveMountEffects @ VM987 chunk-X3B7SAOS.js:18105
flushPassiveEffectsImpl @ VM987 chunk-X3B7SAOS.js:19486
flushPassiveEffects @ VM987 chunk-X3B7SAOS.js:19443
(anonymous) @ VM987 chunk-X3B7SAOS.js:19324
workLoop @ VM987 chunk-X3B7SAOS.js:197
flushWork @ VM987 chunk-X3B7SAOS.js:176
performWorkUntilDeadline @ VM987 chunk-X3B7SAOS.js:384
Show 15 more frames
Show less
VM999 auth-provider.tsx:30 oidc:default:loginCallbackAsync_end {}
VM999 auth-provider.tsx:30 oidc:default:token_aquired {accessToken: 'ACCESS_TOKEN_SECURED_BY_OIDC_SERVICE_WORKER_default', expiresIn: 300, idToken: 'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6IC…gA6LuRoKnPMod7JQIbYV0fqR-UMNoC5AGsKQzpYTDi2MR4E3A', scope: 'openid email offline_access profile', tokenType: 'Bearer', …}
auth-provider.tsx:14 oidc:default:silentLoginAsync_end {}
auth-provider.tsx:14 oidc:default:token_aquired {}
auth-provider.tsx:14 oidc:default:silentLoginAsync_error {reason: 'timeout'}
```

However, the login succeeds as you can see from the `token_aquired` event, but the same issue as with the production-like environment arise: `oidcUser` is null and therefore the avatar renders the fallback instead of the user initials.

**Comment by nicolas-goudry** [comment]
Sorry for the spammy-like messages…

I just found out that there was a special function `reloadOidcUser` provided by the `useOidcUser` hook. So, I wondered what would happen if I forced the user reload when specific conditions were met, and it fixed my first issue !

So, in the production-like environment where the code is served by nginx, I updated my `auth-menu` component to add the following code:

```
  useEffect(() => {
    if (isAuthenticated && !oidcUser && oidcUserLoadingState !== OidcUserStatus.Loading) {
      reloadOidcUser()
    }
  }, [isAuthenticated, oidcUser, reloadOidcUser, oidcUserLoadingState])
```

It now works like a charm with the built-in silent login feature :tada:

However, it worsened the issue in dev, because now the second tab is going into an infinite loop with the `Error: state not valid` error… I guess that for now it’s ok as the issue only arise in development and I don’t really care of multi-tabs login sync in such environment, however it seems that `oidc-client` doesn’t play well with Vite in such case.

**Comment by guillaume-chervet** [comment]
Hi @nicolas-goudry , thank you for all your messages, feedbacks.

I am in holiday until september.
The state error is intersting. I'am searching from a long time how to reproduce it.

I will look at your issue more in detail when i am back and i am happy your found a solution.

**Comment by nicolas-goudry** [comment]
I’ll try to take some time to provide you with a reproducing repository and will let you know about that.

I wish you good holidays :slightly_smiling_face:

**Comment by guillaume-chervet** [comment]
Thank you very much @nicolas-goudry :)

**Comment by nicolas-goudry** [comment]
Ok, I crafted a small repository with as minimal steps to reproduce as possible. It’s available [here](https://github.com/nicolas-goudry/vite-oidc-client-silent-login-issue).

For some reason, I don’t have the infinite loop on call to `reloadOidcUser()` but I do have the same `state not valid` errors in the console. My guess is that this reproducing repo is a very very simple case with a lot less side components than my real application. I hope this is enough for you to debug, let me know when you come back :slightly_smiling_face:

**Comment by guillaume-chervet** [comment]
Thank you so much @nicolas-goudry .
I will start to look at it from my Phone.

**Comment by nicolas-goudry** [comment]
@guillaume-chervet So kind of you, but you shouldn’t.

Enjoy your holidays, there’s no hurry on my side and I would feel bad for you.

**Comment by nicolas-goudry** [comment]
I was just working on my project, and I saw that clearing the cache and forcing the page reload is messing the authentication state. This is also reproducible with the repository I provided.

While being authenticated on Chrome browser with devtools opened, long press on the reload button and select « Empty cache and hard reload » (if the option is not available, you might have to _soft_ reload the page while devtools are opened to get it).

After the hard reload, you will see that the session is lost. However, if you hit again the sign in button, you won’t have to sign in against the OIDC server, you will already be logged in and redirected to the application with a valid token.

**Comment by nicolas-goudry** [comment]
Hi @guillaume-chervet , did you have time to look into this issue yet ? Again, I’m not in a hurry, so it’s not a big deal if you didn’t have time. Just checking :slightly_smiling_face:

**Comment by guillaume-chervet** [comment]
Hi @nicolas-goudry , thank you for your help. I do not forget it i keep it in my head.
Thank you do much for your example itnis so rare !
I will try to look at it this friday!

**Comment by guillaume-chervet** [comment]
Hi @nicolas-goudry , 
I am very sorry I am on too much subjects :p
I try it tomorrow !

**Comment by guillaume-chervet** [comment]
Thank you so much @nicolas-goudry , I can reproduce it. It gold mine to help to fix it. Thank you !

**Comment by guillaume-chervet** [comment]
Hi @nicolas-goudry , it is fixed now :) 
Thanks of your big help :)

May we close the issue ?

**Comment by nicolas-goudry** [comment]
Ooh, neat.

Let me get back to you in a few days, I’ll close the issue if it’s fixed!

**Comment by guillaume-chervet** [comment]
hi @nicolas-goudry , can I close this issue? :)

**Comment by nicolas-goudry** [comment]
I’ll reopen the issue if needed, I’m not working anymore on this project so I can’t tell you if it’s working as expected or not… Sorry.
