### ISSUE TITLE
Can't access role

### ISSUE THREAD

**Issue by linlon13x** [AxaFrance/oidc-client#1082]
### Issue and Steps to Reproduce

I have a `roles` field in my token: 
```
{
  "exp": 1688556466,
  "typ": "Bearer",
  ...
  "roles": [
    "agent",
    "customer"
  ],
  ...
```

and I'm using loaders in my router. 
```
const router = createBrowserRouter([
  {
  id: 'my-page',
  path: 'my-page',
  element: <MyPage/>,
  loader: async () => {...}
  }
]
```
In the loader I have 3-4 request to load data, but I need to access the `roles` value, because I need to determine which request should I send based on the roles (2-2 request each role).

### Versions
@axa-fr/react-oidc": "^6.23.1

#### Expected
Should be able to access the `roles` field.

#### Actual
Can't access.

**Comment by guillaume-chervet** [comment]
Hi @linlon13x, sure you can access to your field.
Try the demo, Access_Token and IT_TOken information are available : https://black-rock-0dc6b0d03.1.azurestaticapps.net/

**Comment by linlon13x** [comment]
@guillaume-chervet 
The loaders aren't in components. They are in ts files as functions. I saw that you can access every token using hooks, but in this case using hooks is not possible. 
Can you please provide an example how to get the roles?

**Comment by guillaume-chervet** [comment]
hi @linlon13x , do you know in which token are defined your role ?
Do you have a sample response of the authorization request? (in the chrome network tab)

It will help to understand your need.

**Comment by guillaume-chervet** [comment]
hi @linlon13x , do you have more information?

**Comment by guillaume-chervet** [comment]
Hi @linlon13x , I close the issue. Feel free to reopen it if you need it
