### ISSUE TITLE
Hard-reload in browser unregister ServiceWorker

### ISSUE THREAD

**Issue by DCosti** [AxaFrance/oidc-client#1098]
### Issue and Steps to Reproduce

When hard-reload in browser, the ServiceWorker seems to be unregistered. He doesn't intercept the calls to inject the token meaning that all the calls will failed with `Unauthorized` error.
After a simple refresh in browser, everything works fine.
This can be reproduce in your [demo react.](https://black-rock-0dc6b0d03.1.azurestaticapps.net/)

### Versions
v6.24.1
### Screenshots
![image](https://github.com/AxaFrance/react-oidc/assets/41594981/1f6875e8-1007-4801-8e89-51a772b79aac)
![image](https://github.com/AxaFrance/react-oidc/assets/41594981/ddff39be-0f76-450d-afec-a83c4ddc5215)
#### Expected
ServiceWorker to intercept and inject token after a hard-reload in browser
![image](https://github.com/AxaFrance/react-oidc/assets/41594981/9ddd81b1-0d44-4ef6-934d-cf299425e2fe)

#### Actual
ServiceWorker isn't injecting token after a hard-reload

Thanks!:)

**Comment by guillaume-chervet** [comment]
Hi @DCosti , thank you for your issue.

Unfortunately it is part of Service Worker specification : https://stackoverflow.com/questions/49054293/serviceworker-fails-on-hard-reload-ctrl-shift-r-in-chrome

**Comment by Thodor12** [comment]
There's an easy way to mitigate this issue, you can check if `navigator.serviceWorker.controller` is present.
If not you can do a regular reload of the window, which is seen as a regular refresh which won't unregister the service worker.

For example:
```ts
const root = ReactDOM.createRoot(
    document.getElementById("root") as HTMLElement,
);

if (navigator.serviceWorker.controller) {
    root.render(
        <React.StrictMode>
            <App />
        </React.StrictMode>,
    );
} else {
    window.location.reload();
}
```

**Comment by DCosti** [comment]
Thanks, @Thodor12 ! I will try it.

**Comment by VladimirPlatonenko** [comment]
> Thank you @Thodor12 , i will try your solution.

Well yes you can detect hard refresh(via navigator.serviceWorker.controller) and refresh page. But you actually can avoid this extra reload and fix problem in place. All you need is claim all clients from SW. 
I have created PR with this solution.

**Comment by Thodor12** [comment]
I actually have not noticed this problem anymore in newer versions of oidc-client. So this may not be necessary anymore.
