### ISSUE TITLE
Token refresh every second and resetting every react-state

### ISSUE THREAD

**Issue by bohrsty** [AxaFrance/oidc-client#1114]
### Issue and Steps to Reproduce

I try to use this library to authenticate against nextcloud [oidc app](https://github.com/H2CK/oidc), without service worker. Authentication and all necessary redirect work like expected, but the library calls the token refresh endpoint every second (see screenshot), although the token expires in 15 minutes (900 seconds, like on the right part of the screenshot). An additional effect of refreshing the token every second is, every react-state I use (or every uncontrolled component I use) below the `OidcProvider` component, is reset to its initial state every second, what makes the the app useless.

My react-oidc configuration is the following:
```js
{
        client_id: state.config.oidcClientId,
        redirect_uri: `${window.location.origin}/authentication/callback`,
        silent_redirect_uri: `${window.location.origin}/authentication/silent-callback`,
        scope: 'openid profile groups offline_access',
        authority: state.config.oidcAuthority,
        service_worker_only: false,
    }
```
where `state.config` is a wrapper to get the configuration values from environment into the app.

### Versions
```
├── @axa-fr/react-oidc@6.24.23-alpha914
├── @emotion/react@11.11.1
├── @emotion/styled@11.11.0
├── @fontsource/roboto@5.0.5
├── @mui/icons-material@5.14.0
├── @mui/material@5.14.0
├── @types/react-dom@18.2.7
├── @types/react@18.2.15
├── @vitejs/plugin-react@3.1.0
├── axios@1.4.0
├── express@4.18.2
├── react-dom@18.2.0
├── react-router-dom@6.14.1
├── react@18.2.0
├── vite-express@0.9.1
└── vite@4.4.4
```

### Screenshots
![Screenshot](https://github.com/AxaFrance/react-oidc/assets/2415071/799ad342-accc-486b-818d-ba1b7bf025ed)

#### Expected
Token refresh happens after 13 minutes and react-states are never reset to initial state.

#### Actual
Token refresh every second and reset of every subsequent react-state to its initial state every second.

Any help would be appreciated...

**Comment by guillaume-chervet** [comment]
Hi @bohrsty , thank you for using react oidc.

I will need more code détail to understand you problem.
This problem generaly happen when you create dynamical react component inside render of a component. It is a normal react behavior, it rerender all component beside because it is always a new component.
My collegues do this error often inside routine component. 
 The solution is to create component outside.

**Comment by bohrsty** [comment]
Thanks for your reply @guillaume-chervet, I'm not entirely sure what you mean by "dynamical react component"... does it mean something like this?
```jsx
export const SomeComponent = () => {
  // do something
  // is this a dynamical react component???
  const SomeOtherComponent = () => {
    return(<p>content</p>);
  }

  return(<SomeOtherComponent />);
}
```

If yes, I cannot find anything like this in my whole code... I haven't set up a repository with my complete code yet, but I created a [gist](https://gist.github.com/bohrsty/21b9e4b2372a9e3b1ac50010d229a572) with (in my opinion) the relevant parts using react-oidc. The behaviour has started with this components, anything that comes later down the router tree is only effected...

I wrapped a component (`Authentication.jsx`) around react-oidc, because I want to be able to add more authentication modules later, that should use the same "interface".

The whole thing is driven by vite and express (package `vite-express`), the entrypoint is the default `main.jsx` from vite...

I hope, the code examples show you more to investigate than me, if you cannot find anything either, please ask for details, that may help... If nothing helps, the last step could be, that I set up my repository and show the complete code...

Thanks and regards
bohrsty

**Comment by guillaume-chervet** [comment]
Hi @bohrsty , yes exatcly like your describe.
I do not see one in the code you give.

What happen if your init browserrouter after the oidcprovider like in the demo? https://github.com/AxaFrance/react-oidc/blob/main/examples/react-oidc-demo/src/App.tsx

**Comment by bohrsty** [comment]
There might have been a reason, why I didn't follow your docs (I can't remember it yet), but putting the router inside the oidc-provider doesn't change the issue...

**Comment by guillaume-chervet** [comment]
Hi @bohrsty , dobyou have the code of Home component?

**Comment by bohrsty** [comment]
Yes, I do, but there isn't much it does (it's just returning `null`)... I added the `Home` and the `Root` component to the gist, there you can have a look at it...

**Comment by guillaume-chervet** [comment]
Thank you @bohrsty, I'am trying to reproduce it on the demo.

**Comment by guillaume-chervet** [comment]
It's may be link somehow to #1110.
But I have the same kind of configuration on my project, and i Cannot reproduce it.

**Comment by guillaume-chervet** [comment]
hi @bohrsty , I cannot reproduce it on the demo.

Are you able to reproduce it?

I'am using field input firstname to check react child component state with the demo on the route :
https://black-rock-0dc6b0d03.1.azurestaticapps.net/multi-auth

**Comment by guillaume-chervet** [comment]
![introduction](https://github.com/AxaFrance/react-oidc/assets/52236059/e08c761f-6a2d-4848-a257-df1ddef44e14)

like in #1110 I'am stuck to reproduce it.

**Comment by bohrsty** [comment]
I made a bit of progress, I think I found the state resetting "dynamical react component". I missed a `useRoutes()` call somewhere in one of my components and forgot about that it returns a react component... After I refactored that component, the state reset is gone and the app usable, but  the every-second-token-refresh stays...

**Comment by guillaume-chervet** [comment]
Hi @bohrsty go news for the first point.
For the second, which oidc provider are your using? How llife span long is your token?

**Comment by bohrsty** [comment]
I use the https://github.com/H2CK/oidc provider and the token life time settings are 15 minutes... and as you can on the screenshot in see in my first comment, the `expires_in` field is set to 900, so this seems correctly given to the client...

**Comment by guillaume-chervet** [comment]
Hi @bohrsty do you have a sample of an access token + oidc token?

The defaut code about  your problem:
https://github.com/AxaFrance/oidc-client/blob/e74c0df57140ca2bd3c7fd631eef39661b1b2b8c/packages/oidc-client/src/parseTokens.ts#L72

**Comment by bohrsty** [comment]
This is returned, if the `token_endpoint` is called:

```json
{
  "access_token":"opqavdgHEYx8nhCdc3iByd1HD0jiYN30LevhJy4f5wIavINXKdh4lQ9C3kA49QF0OH0XeA02",
  "token_type":"Bearer",
  "expires_in":"900",
  "refresh_token":"DEsqDca7nDGSgT6tJPkCwbPy98B8VOC4AA55lOPs03G3hqhZ8WH08REBcwTZg1s0jZyVoA3iCXzm4PPJ096gjV7ZKYyN8vnFKw6P6KLV3tUI6mWFaSROoh1LipThFrkS",
  "id_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjUwNWZkODljLTM4YzktNGI2Mi04ZjQ3LWI4MGQ0ZTNhYjYxNSJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODA4MCIsInN1YiI6ImFkbWluIiwiYXVkIjoiM2FTbk5XUGxZQWQwOGVES3c1UUNpSWVMcWpIdHkxTTVzSGFzcDJDZWREcWYzbmJkZm8xUFo1cXhmbWoyaFhkUyIsImV4cCI6MTY5MDk4NzQ1NCwiYXV0aF90aW1lIjoxNjkwOTg2NTUxLCJpYXQiOjE2OTA5ODY1NTQsImFjciI6IjAiLCJhenAiOiIzYVNuTldQbFlBZDA4ZURLdzVRQ2lJZUxxakh0eTFNNXNIYXNwMkNlZERxZjNuYmRmbzFQWjVxeGZtajJoWGRTIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRtaW4iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGdyb3VwcyBvZmZsaW5lX2FjY2VzcyIsIm5iZiI6MTY5MDk4NjU1NCwianRpIjoiNjMiLCJub25jZSI6ImNpQkVVOTdaVmRWVSIsImdyb3VwcyI6WyJhZG1pbiJdLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsInVwZGF0ZWRfYXQiOjE2OTA5ODY1NDV9.2MUdtQR_QtzDY9BTMctG8C4uvg92DgMIUUoJed2cI7WTd5_VEPFW87esDQLw4snVdAJM1_Wf3wB88B2MXFDMCnMTNn0TMnzetRDiG3xlr2LL-geL5SNgwD0Y6RPK_aITjrC9uiQCTj3LPEENrBulNRZPURwaVon9WUVNuuBmMTKd7QKEuFN0zYDoRs0HnXo6WKnFy1rldLGh_JpA3PBUuXt4VMjfGQ7yYEuNn7MkFVDX6OnTffR8jTQp74hREvuRLFjYxfgfgu547X7yIcboOl81D0ZQlP-gfvBOeypZolRLScuqAA3fHBYvE0vCtOM6ObekfeeTDfms75csMLUuZtTR07x32xYC8vdoFsY0sRpMByTqlhsae9VX_rETJ7PIWEfruojzcj47WN9dG0K3pdPiJHEwZ1CKgZfU_cY0gtuAGaIcIjKL0txXCevaiIiIsrgSU_HTjNVybp4WHSAs3h6x0XLz4_91luCylsaoMQbwKOQNwAfr2L74jF6DOg-8DIPb-WClRQzaQtrkx_iv6FtqCB3ogFoZwi6xljdYUc2EHUmoAo-LXal-QAgUXGGzfFU2YOpxV3RyAbMGPm7PfkMVzDsDJwORJNhh38QQ6o88GgNnV28BT-d2G0n7okc0QC6o2IW0jpyCrI6v0hWOBUX2EqiJ5Wao-4LYZfCaRgU"
}
```

Is this what you mean?

**Comment by guillaume-chervet** [comment]
thank you @bohrsty it is exactly what I need.

**Comment by bohrsty** [comment]
As far as I can see in my browser, with this version it has stopped refreshing the token every second... It has refreshed the first time after 799 seconds now, which is a great relief for my browser... thank you very much!

**Comment by guillaume-chervet** [comment]
So cool. I will finish the pullrequest and merge it today @bohrsty .
Thankbyoi for the feedback.

**Comment by guillaume-chervet** [comment]
You can now use version v7.0.1 :)
Thank you very much @bohrsty for your help and feel free to close the issue if it works.

**Comment by bohrsty** [comment]
It still works with v7.0.1... thank you @guillaume-chervet for your quick and professional help and fix and to all the dev-team for this very useful package...
