### ISSUE TITLE
Access token is being sent with synchronous http requests to backend  APIs

### ISSUE THREAD

**Issue by oussamaAbdelwahed** [AxaFrance/oidc-client#1117]
### Issue and Steps to Reproduce

Hello, i'am using the service worker auth approach and i noticed that the access token is always sent with synchronous HTTP requests to our backend API (for example when opening a new  browser tab and accessing an backend endpoint URL via GET method --> got a json RAW response)

### Versions
^6.18.0
### Additional Details
I was wondering if there is a way to prevent the described behavior, thank's in advance.
- Installed packages:

**Comment by guillaume-chervet** [comment]
hi @oussamaAbdelwahed, thank you for your issue.

I'am not sure, but on the lastest version it should not have this beahvior. We have the configuration attribute named service_worker_convert_all_requests_to_cors : Bolean to control That.

You can also fine grain your trusted domain url to exclude some urls.

**Comment by oussamaAbdelwahed** [comment]
@guillaume-chervet, basically , all i want is to prevent service worker from attaching the Authorization header to the synchronous GET request initiated by the browser , 
![Uploading oidc.png…]()

**Comment by oussamaAbdelwahed** [comment]
setting **service_worker_convert_all_requests_to_cors: false** solved the problem, thank's.

**Comment by oussamaAbdelwahed** [comment]
I solved the issue just by ignoring the setup of the Authorization header when originalRequest.mode === "navigate"
`  const newRequest =
      originalRequest.mode === 'navigate'
        ? new Request(originalRequest, {
            headers: {
              ...serializeHeaders(originalRequest.headers),
              // authorization:
              //   'Bearer ' +
              //   currentDatabaseForRequestAccessToken.tokens.access_token,
              // some testing comment
            },
          })
        : new Request(originalRequest, {
            headers: {
              ...serializeHeaders(originalRequest.headers),
              authorization:
                'Bearer ' +
                currentDatabaseForRequestAccessToken.tokens.access_token,
            },
            mode: currentDatabaseForRequestAccessToken.oidcConfiguration
              .service_worker_convert_all_requests_to_cors
              ? 'cors'
              : originalRequest.mode,
          });`
I think that it will be cool if we can achieve this using a dedicated configuration attribute.

**Comment by guillaume-chervet** [comment]
Totaly aggree @oussamaAbdelwahed

**Comment by guillaume-chervet** [comment]
Hi @oussamaAbdelwahed , i will try to add it today.

**Comment by guillaume-chervet** [comment]
hi @oussamaAbdelwahed, sorry for the delay,
I'am thinking of moving these properties to TrustedDomains.js.

I need the week-end to think :)

**Comment by guillaume-chervet** [comment]
hi @oussamaAbdelwahed ,

version 7.3.0-alpha.1020 should do the job.

You will need to update your TrustedDomains.js.


 ```

// Service worker will continue to give access token to the JavaScript client
// Ideal to hide refresh token from client JavaScript, but to retrieve access_token for some
// scenarios which require it. For example, to send it via websocket connection.
trustedDomains.config_show_access_token = { 
    domains: ['https://demo.duendesoftware.com'], 
    showAccessToken: true,
    // convertAllRequestsToCorsExceptNavigate: false,
    setAccessTokenToNavigateRequests: true,
};

 ```

**Comment by oussamaAbdelwahed** [comment]
@guillaume-chervet cool thank's

**Comment by guillaume-chervet** [comment]
I published it to version 7.3.0 @oussamaAbdelwahed .Tell me if it works :)

**Comment by oussamaAbdelwahed** [comment]
@guillaume-chervet yeah sure

**Comment by oussamaAbdelwahed** [comment]
@guillaume-chervet  this doesnt work as expected, i was debugging the code inside OidcServiceWorker.js using a console.log(  currentDatabaseForRequestAccessToken.setAccessTokenToNavigateRequests); inside handleFetch function and i always got a true value even though i set trustedDomains.config_show_access_token.setAccessTokenToNavigateRequests to false inside OidcTrustedDomains.js

**Comment by guillaume-chervet** [comment]
Hi @oussamaAbdelwahed , thank you for your feedback.
Do you have a full example of your trusteddomains.js file?

**Comment by oussamaAbdelwahed** [comment]
const trustedDomains = {
  default: ['*'],
};


trustedDomains.config_show_access_token = {
  domains: ['*'],
  showAccessToken: true,
};

trustedDomains.config_separate_oidc_access_token_domains = {
  oidcDomains: [https://'my-oidc-server/*'],
  accessTokenDomains: ['*'],
};

**Comment by oussamaAbdelwahed** [comment]
@guillaume-chervet  i updated the code in the previous comment

**Comment by oussamaAbdelwahed** [comment]
@guillaume-chervet  no, my bad, in fact i'am using the default configuration (i does not set configurationName prop), so i guess i just should set the setAccessTokenToNavigateRequests directly inside the trustedDomains object definition

**Comment by guillaume-chervet** [comment]
Hi @oussamaAbdelwahed , 
Yes something like 

```javascript
// Service worker will continue to give access token to the JavaScript client // Ideal to hide refresh token from client JavaScript, but to retrieve access_token for some // scenarios which require it. For example, to send it via websocket connection. trustedDomains.default = { domains: ['https://demo.duendesoftware.com'], showAccessToken: true, // convertAllRequestsToCorsExceptNavigate: false, setAccessTokenToNavigateRequests: true, }; 


```

**Comment by oussamaAbdelwahed** [comment]
@guillaume-chervet  i'a currently suing this config 

trustedDomains.default = {
  domains: ['*'],
  showAccessToken: false,
  convertAllRequestsToCorsExceptNavigate: true,
  setAccessTokenToNavigateRequests: false,
};

and still got access token attached to navigate requests

**Comment by guillaume-chervet** [comment]
Hi @oussamaAbdelwahed thank tou fir your feeback.
The default value exist for not creating à breaking change. In your case it should return the configured value.
I am in holiday whithout computer until 4 september.

I cannot help you more until that date :p

**Comment by oussamaAbdelwahed** [comment]
@guillaume-chervet i believe the cause is behind the instruction in line 588 inside handleMessage : 
```
   setAccessTokenToNavigateRequests:
        doNotSetAccessTokenToNavigateRequests || true,
```
setAccessTokenToNavigateRequests will be always  true if setAccessTokenToNavigateRequests is undefined, null or false. I believe this can be fixed just using the javascript nullish coalescing operator :
```
setAccessTokenToNavigateRequests:
        doNotSetAccessTokenToNavigateRequests ?? true
```
I tested it and it works as expected.

What do you think ?

**Comment by guillaume-chervet** [comment]
hi @oussamaAbdelwahed , version 7.4.1 contain your fix :)

**Comment by oussamaAbdelwahed** [comment]
@guillaume-chervet , it worked , thank's.
