### ISSUE TITLE
ServiceWorker.js issue can't be initialized

### ISSUE THREAD

**Issue by antosimi** [AxaFrance/oidc-client#1122]
### Issue and Steps to Reproduce

Hi i added last version of oidc-client : "@axa-fr/react-oidc": "^7.0.1", but i get : 

![image](https://github.com/AxaFrance/oidc-client/assets/44970315/ff68a9d7-8640-4dc3-be54-142bc89c27f4)

I have in public folder a Service worker.js. This is the config: 
![image](https://github.com/AxaFrance/oidc-client/assets/44970315/adcaed7c-4d08-4c04-9ae9-063299ce78e6)

I added the oidc provider in App.tsx and it includes all the routes.
This is where i use it in the LoginForm.tsx:
![image](https://github.com/AxaFrance/oidc-client/assets/44970315/d48a52b8-f584-4d37-9818-615dc67556f2)
Maybe I am missing something, or it could be a bug ?

P.S. I have 2 more questions for better understanding the flow, is there a default redirect_url I can use in order for the oidc-client package to manage the oauth2 login till I get the token, because I don't want to actually create the requests from scratch, or where in the examples on github is the resirect url treated ? The second question is regarding the  OidcTrustedDomains , I see I need to add my localhost:3000. but should I let the others domains in that file, or just complete with mine, and it is mandatory to change that file in order to function ? Thank you.

**Comment by guillaume-chervet** [comment]
I @antosimi, thank you for your Issue and using react-oidc.

I'am not sure, but I think you service_worker_relative_url should be OidcServiceWorker.js without public folder.

The javascript code try to register the ServiceWorker but does not find it.

**Comment by antosimi** [comment]
Yes that was the mistake, thank you.  But unfortunately now i have the error, if you have any suggestions
![image](https://github.com/AxaFrance/oidc-client/assets/44970315/755ebd2e-d333-4f64-92db-7ba91abc4cdd)

**Comment by guillaume-chervet** [comment]
hi @antosimi ,

It is some configuration to configure at google side.

**Comment by antosimi** [comment]
I understand but there is a strange behaviour, when I use the configuration from the exaple with : https://demo.duendesoftware.com works fine, but when I try just to add the path to google for oauth2 login. I have added in App.tsx where I declared the path routes the OidcProvider. Even tho I the /login page I have a button which should trigger  onclick() the login() from useOidc(). Just when I enter the /login page it tries to make a fequest and then there is the above error with CORS issue. The strange behaviour is why is making the request by itself on /login page just because is in OidcProvider, but when I tryed other server it did worked.

**Comment by antosimi** [comment]
I managed to fixed all : my configuration was not okay : I did not specify the authority_configuration( where i specify all the endpoints)
![image](https://github.com/AxaFrance/oidc-client/assets/44970315/95a94669-2109-47e4-bd97-e7e62ef819b9)

**Comment by antosimi** [comment]
Just a quick question I got to the point to get token but the error is : 
![image](https://github.com/AxaFrance/oidc-client/assets/44970315/9b2de887-65d3-4bd1-a13a-4381d30aae02)

Seems that the service token is crying because the token is not valid.
But when i got to network in inspect element mode : 
![image](https://github.com/AxaFrance/oidc-client/assets/44970315/1ff59330-4ca4-4fb4-8f2c-30d42318fe87)

Th first /token says : (failed)net::ERR_FAILED , but there is a second /token underneath that response with exactly what i need access_token an id_token. Is there a posibility to make service worker wait longer for the response ?

**Comment by guillaume-chervet** [comment]
hi @antosimi , do you have always this error?
I will publish a version with more log detail.

**Comment by guillaume-chervet** [comment]
hi @antosimi ,

I just publish version 7.2.2 with a lot of more log details to understand your problem.

**Comment by antosimi** [comment]
yes , i checked a bit and i think the issue is with the is valid() in service worker , right now the google sends me id_token(which can be parsed and it returns info), but the access_token has changed the aspect i guess, like in here:
const extractTokenPayload = (token) => {
  try {
    if (!token) {
      return null;
    }
    if (countLetter(token, ".") === 2) {
      return parseJwt(token);
    } else {
      return null;
    }
  } catch (e) {
    console.warn(e);
  }
  return null;
};

The countLetter(token, ".") === 2) is not a valid check since the access_token does not have 2 points. I may be wrong but this is what i guess. I found a person having a similar issue, maybe it helps to update the validating of access token https://github.com/parse-community/parse-server/issues/6849 @guillaume-chervet

**Comment by guillaume-chervet** [comment]
hi @antosimi ,

this case is managed by the library.

![image](https://github.com/AxaFrance/oidc-client/assets/52236059/24a1071c-3cf3-4bf8-8cf9-178b4268dc97)


Are you able to display the console message using the version 7.2.2?

**Comment by antosimi** [comment]
@guillaume-chervet  not sure the version 7.2.2 of what ? i updated right now the @axa-fr/react-oidc to 7.2.0, but right now when I open my app , it goes into a loop and recalls the page over and over again.

**Comment by antosimi** [comment]
Fixed it by multiple tryings to uninstall and install version 7.1.0

**Comment by antosimi** [comment]
Well now all works, thank you so much  for the support! @guillaume-chervet

**Comment by antosimi** [comment]
My issues were : 
- not putting the correct path to OidcServiceWorker, it just needs to be '/OidcServiceWorker.js';
- not having a matching issuer with the one extracted from token_Id;
- some issue with npm when i upgraded to newest version;

**Comment by guillaume-chervet** [comment]
Thank you for the feedback @antosimi 😀
I Hope you will have fun with react oidc!
