### ISSUE TITLE
@axa-fr/react-oidc: postinstall script to copy service worker files does not work

### ISSUE THREAD

**Issue by NicerDicerPro** [AxaFrance/oidc-client#1124]
### Issue and Steps to Reproduce

Running the postinstall script by hand or as actual "postinstall" script in npm does result in various errors.

Note: as the project im working on is classified i substituted the actual project root folder name by "projectname" in all occasions.

Using the commands from https://github.com/AxaFrance/oidc-client#getting-started-with-axa-frreact-oidc

`node .\node_modules\@axa-fr\react-oidc\bin\copy-service-worker-files.mjs public`

results in:

```
node .\node_modules\@axa-fr\react-oidc\bin\copy-service-worker-files.mjs public
node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module '/Users/schoef1/Projects/projectname/.node_modules@axa-frreact-oidcbincopy-service-worker-files.mjs'
    at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Module._load (node:internal/modules/cjs/loader:804:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.7.0
```

Using the npm script via `npm run postinstall`:

```
"scripts": {
  "postinstall": "node .\\node_modules\\@axa-fr\\react-oidc\\bin\\copy-service-worker-files.mjs public"
},
```

results in the same error:

```
npm run postinstall

> projectname@0.3.27 postinstall
> node .\node_modules\@axa-fr\react-oidc\bin\copy-service-worker-files.mjs public

node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module '/Users/schoef1/Projects/projectname/.node_modules@axa-frreact-oidcbincopy-service-worker-files.mjs'
    at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Module._load (node:internal/modules/cjs/loader:804:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.7.0
```

As both of the above errors obviously are telling that the module could not be found as the backslashes are generating trouble i tried calling the script by hand and by `npm run postinstall` with forwardslashes:

`node ./node_modules/@axa-fr/react-oidc/bin/copy-service-worker-files.mjs public`

Which results in the following error (for both running by hand and via `npm run postinstall`):

```
node ./node_modules/@axa-fr/react-oidc/bin/copy-service-worker-files.mjs public
[oidc-client:skip] file does not exist /Users/schoef1/Projects/projectname/node_modules/@axa-fr/react-oidc/node_modules/@axa-fr/oidc-client-service-worker/dist/OidcServiceWorker.js
[oidc-client:skip] file does not exist /Users/schoef1/Projects/projectname/node_modules/@axa-fr/react-oidc/node_modules/@axa-fr/oidc-client-service-worker/dist/OidcTrustedDomains.js
```

I think theres something wrong with the paths inside the copy-service-worker-files.mjs script.

### Versions
7.3.0

### Additional Details

The automatic updates of the service worker files prior to version 7.2.0 worked perfectly fine.

OS is MacOS 13.4.1 on a MacBook Pro M1 Max 2021

**Comment by guillaume-chervet** [comment]
Thank you @NicerDicerPro for your feedback.
I understand the problem, I try to fix it quickly.

**Comment by guillaume-chervet** [comment]
hi @NicerDicerPro , I cannot test on mac, but version 7.3.1 may fix your problem.

**Comment by NicerDicerPro** [comment]
> hi @NicerDicerPro , I cannot test on mac, but version 7.3.1 may fix your problem.

Thank you!
I'll check tomorrow and will let you know if it's fixed 👍

**Comment by NicerDicerPro** [comment]
Works fine in both manual and postinstall execution:

```
node ./node_modules/@axa-fr/react-oidc/bin/copy-service-worker-files.mjs public
[react-oidc:copy] /Users/schoef1/Projects/projectname/public/OidcServiceWorker.js
[react-oidc:skip] file exists not overwriting /Users/schoef1/Projects/projectname/public/OidcTrustedDomains.js
```

Thanks for the quick response and fix!

**Comment by guillaume-chervet** [comment]
Thank you for your help and feedback @NicerDicerPro
