### ISSUE TITLE
Service worker does not work with trusted types

### ISSUE THREAD

**Issue by Bewalticus** [AxaFrance/oidc-client#1125]
### Issue and Steps to Reproduce

We use a content security policy with "require-trusted-types-for 'script';" to increase security of our application. Unfortunately the OidcServiceWorker does not work with it.

Steps:
1. integrate react-oidc in application as described in the documentation and verify it is working
2. add the policy "require-trusted-types-for 'script';" to the Content-Security-Policy response header
3. try to access application in the browser (possibly a reregistration of the service worker in the browser is needed to start from clean)

### Versions

3.7.1

#### Expected

Login in application works as before.

#### Actual

Browser shows: "An error occurred during authentication"

Javascript console shows:
```
OidcServiceWorker.js:240 This document requires 'TrustedScriptURL' assignment.
(anonymous) @ OidcServiceWorker.js:240
OidcServiceWorker.js:240    Uncaught TypeError: Failed to execute 'importScripts' on 'WorkerGlobalScope': This document requires 'TrustedScriptURL' assignment.
    at OidcServiceWorker.js:240:7
(anonymous) @ OidcServiceWorker.js:240
mydomain.com/:1 Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('https://mydomain.com/') with script ('https://mydomain.com/OidcServiceWorker.js'): ServiceWorker script evaluation failed
```

### Additional Details

We temporarily fixed the issue by adding the following lines of code after the first line of OidcServiceWorker.js file:
```javascript
if ((typeof trustedTypes !== 'undefined') && (typeof trustedTypes.createPolicy == 'function')) {
  trustedTypes.createPolicy('default', {
    createScriptURL: function(url) {
      if (url == scriptFilename) {
        return url;
      } else {
        throw new Error('Untrusted script URL blocked: ' + url);
      }
    },
  });
}
```

**Comment by guillaume-chervet** [comment]
Thank you very much @Bewalticus for your issue.
I have to read about this security.

i'am in holiday for 3 weeks. I can manage this in september.

**Comment by Bewalticus** [comment]
@guillaume-chervet, do you have any update here?

**Comment by guillaume-chervet** [comment]
hi @Bewalticus , very sorry for the delay :)

version 7.6.0 implement it :)

**Comment by Bewalticus** [comment]
@guillaume-chervet , thank you for putting it into the release. It works like a charm!

**Comment by guillaume-chervet** [comment]
Thank you for your feedback @Bewalticus  !
