### ISSUE TITLE
Configure "client_secret" without exposing it

### ISSUE THREAD

**Issue by johnnypea** [AxaFrance/oidc-client#1127]
How can one configure "client_secret" without exposing it to the browser? 

As I understand I can't call `OidcClient.getOrCreate` server side.

Thank you.

**Comment by guillaume-chervet** [comment]
Hi @johnnypea , client secret is build for oidc at side.
Often you ear of BFF, backen for frontend.

**Comment by johnnypea** [comment]
Yes, I understand that, but still not sure how can I use `loginAsync` and `loginCallbackAsync` from backend when both of them require "window". Thanks.

**Comment by guillaume-chervet** [comment]
Hi @johnnypea , this library only manage oidc at pure client side.
If you need to use client_secret it is possible but client secret will never be secret.

You can use OIDC at server side using libraries that depends of your technical stack. Server authenticate and manage access token and refresh token. Javascript client authenticate by using a cookie.

**Comment by guillaume-chervet** [comment]
I love https://documentation.openiddict.com/

**Comment by johnnypea** [comment]
ok, I fully understand now, thank you for your time.

For anyone interested this one looks good for Node https://github.com/panva/node-openid-client
