### ISSUE TITLE
How to programatically log the user with the code I got from the callback?

### ISSUE THREAD

**Issue by ifigueroap** [AxaFrance/oidc-client#1135]
I'm working on a Ionic-React + Capacitor application that uses axa-fr/react-oidc for authentication with AWS Cognito. Everything works fine on the web application, but now I'm packaging the app in Android... I managed to get the proper deeplink from Cognito, which is detected by a handler in my code.

I get a url like `my-scheme://oauth2/callback?code=XXXXXXXXXX`  but now I don't know what to do to continue with the authentication flow. What method should I call now with the given code?

Thanks

**Comment by guillaume-chervet** [comment]
Hi @ifigueroap , thank your for your issue.
I do not know about ionic react capacitor but i can try to help with pleasure.
I am not sure but the method is not exposed by react oidc but you can use oidc client directly for the callback:
https://github.com/AxaFrance/oidc-client/blob/823a3c37351e39b0bb1290228f72c58f11a28960/examples/oidc-client-demo/src/index.tsx#L103
It is the library used under the hood so it should work.
I am not sure the regex will work but i will add a test on it tomorrow.

**Comment by ifigueroap** [comment]
Thanks Guillaume for your response, I have managed to make it work! Although now the logout link in our app is not working, I will check why... am I missing something in the promise resolution?

This is the way for anyone using Capacitor and deeplinks:

```js
const DeeplinkHandler: React.FC = () => {
  /* ******************************************************************************/
  /* Register handler for deeplink callback (authConfiguration is defined before) */
  const vanillaOidc = OidcClient.getOrCreate(() => fetch)(authConfiguration);

  useEffect(() => {
    CapApp.addListener("appUrlOpen", async (urlOpenEvent) => {
      console.log(`Got deeplink appUrlOpen with url: ${urlOpenEvent}`);
      const splitURL = urlOpenEvent.url.split("//").pop();
      console.log(`Got splitURL: ${splitURL}`);
      if (splitURL) {
        const newURL = `${window.location.protocol}//${splitURL}`;
        console.log("Push splitURL: " + newURL);
        window.location.replace(newURL);
        console.log("After pushh split ");
        vanillaOidc.loginCallbackAsync().then(() => {
          console.log("After logincallback");
        });
      }
    });
  }, []);
  return null;
};
```

This component is inside the `BrowserRouter` but outside the `OidcSecure` element:
```
    <OidcProvider
      configuration={authConfiguration}
      loadingComponent={() => (
        <IonApp>
          <IonPage>
            Loading...
          </IonPage>
        </IonApp>
      )}
    >
      <BrowserRouter>
        <DeeplinkHandler />

        <OidcSecure>
          .... 
        </OidcSecure>
      </BrowserRouter>
```

**Comment by ifigueroap** [comment]
When the app is cold-started again, it requires login, whereas in the web browser, the session is restored from SessionStorage. Any clues on how/why to make it work in a hybrid app?

**Comment by guillaume-chervet** [comment]
Hi @ifigueroap ,

Thank you very much for your feedback, it is a good news.

May you print a copy of the console.log displayed by your code ? It will help me to understand the logout problem.

Your code sound good for the logout. logout is just a redirection to an oidc server url with idtoken in query string.

About the session, I do not know how work ionic react capacitor. Do you have a sample of your OIDC configuration ?

**Comment by guillaume-chervet** [comment]
Hi @ifigueroap , did you succed ?

**Comment by ifigueroap** [comment]
Sorry I haven't replied back. I noticed that even in our PWA the login is not "persistent". I'm not sure if it's because we are using the library incorrectly, or if is something related to AWS Cognito :/

FWIW, we are using session storage to, welp, store the tokens... and every time I go to the website from scratch, it prompts me with the OAuth/Cognito login redirect. However, once logged in, I can refresh the tab and I'm still logged in.

Is it because we are somehow not storing something? or perhaps de refresh tokens are expired? Or does session storage expire when I close the tab?

**Comment by guillaume-chervet** [comment]
Hi @ifigueroap , did you try to setup localstorage instead of sessionstorage?

sessionStorage life end when browser or page is closed.

localStorage keep living when page is closed or browser os closed.

**Comment by ifigueroap** [comment]
Thanks for the tip, I will try that. Regarding this issue, I think it can be closed as I managed to log in "programatically", as shown above. Thanks a lot!
