### ISSUE TITLE
Special character ignored in request

### ISSUE THREAD

**Issue by LucaNitti** [AxaFrance/oidc-client#1140]
### Issue and Steps to Reproduce

I use useOidcFetch from @axa-fr/react-oidc to make call to a BE.
When i inser some special character (Eg: #) the character will be removed from url.

I tried to pass the information in options, but the package seems to ignore everything that i put in option,

Version used ^6.25.6

**Comment by guillaume-chervet** [comment]
Hi @LucaNitti , do you have more information about your problem?

**Comment by guillaume-chervet** [comment]
hi @LucaNitti , I close the issue.
if you have more information or more detail, you can continue to give it so I will reopen it .
