### ISSUE TITLE
Service worker is only working after 2 seconds after auth process

### ISSUE THREAD

**Issue by HSULGIT** [AxaFrance/oidc-client#1144]
I need to fetch data from an python endpoint directly after auth in react. In some scenarios in the past i had the problem that the service worker needed some time to get fully initialized (1-2 seconds) in order to inject the bearer token. That caused a 401 in the first 1-2 tries. Now it seems the worker starts fast enough. But in order to prevent unneeded fetches with 401 in the future, is there a function that gives information about the state of the service worker so i can execute my fetch after service worker is fully initialized and ready to inject the bearer token?

**Comment by guillaume-chervet** [comment]
Hi @HSULGIT ,

If you are using service worker. It now make automaticaly the fetch wait for the synchronsation to be finished before continuer to trigger the request to the server.

If not the fetch retrun by "useFetch" do it internally.

**Comment by HSULGIT** [comment]
So it got fixed while I was on vacation. Very good. Thank you!
