### ISSUE TITLE
token_endpoint_auth_method  can be only client_secret_post 

### ISSUE THREAD

**Issue by antosimi** [AxaFrance/oidc-client#1146]
Hello I am intrested if the library only communicates for token as "client_secret_post", or is there any property in configuration I can change so that the token_endpoint_auth_method  could be : client_secret_jwt and the request for token can be send accordingly.

**Comment by guillaume-chervet** [comment]
Hi @antosimi , thank you for your issue .
I am not sure to understand it.

You can send secret like that: https://github.com/AxaFrance/oidc-client/blob/4f9b3c0b767d4b955223febcc833e6ff47e997ef/examples/react-oidc-demo/src/configurations.ts#L88

But it won't be secret anymore :)

**Comment by antosimi** [comment]
Thank you for your answer, I am talking about this : [https://cloudentity.com/developers/basics/oauth-client-authentication/client-secret-authentication/](url)  . In this article you can see there are multiple ways you can send the secret.
client_secret_basic : you send in header 
client_secret_post : you send it in body ( this is the one this library seems to use)
client_secret_jwt : you send the token more encrypted and is more secure. ( this is the way I am interested to send my client_secret when requestion post)

My question is: is there a way you can send it like that ?

**Comment by guillaume-chervet** [comment]
Hi @antosimi , I am not sure it is a suitable mode for a client javascript.

For that case the documention you give redirect on PCKE mode supported by react oidc and oidc client : https://cloudentity.com/developers/basics/oauth-client-authentication/client-auth-set-to-none-with-pkce

**Comment by antosimi** [comment]
I am not able to access the link

**Comment by antosimi** [comment]
But i fiexed it by changing my config to the client i am involving outh2 to expect client_secret_post from my side
