### ISSUE TITLE
Fast timeout

### ISSUE THREAD

**Issue by antosimi** [AxaFrance/oidc-client#1148]
After a successfull login using this library the app is getting Session expired after not even an entire minute:
![image](https://github.com/AxaFrance/oidc-client/assets/44970315/8f85de23-63e6-4f5e-bf6d-dc11eeef0bb6)

Is there a posibility to change the timeout from service worker ?

Thank you.

**Comment by guillaume-chervet** [comment]
Hi @antosimi , 
Thank you for your issue.
What is your configuration?
do you have a sample of your access token?

Which browser are you using?

**Comment by antosimi** [comment]
Thank you @guillaume-chervet for the quick response. I am using 7.1.0 version. I an using google. Maybe is an issue with the silent-login not having timeout ? not really sure what silent login is, but is only timeout i see in config

```
export const oauth2Configuration :OidcConfiguration = {
  client_id : XXX
  redirect_uri : window.location.origin + '/authentication/callback',
  scope : 'openid email',
  authority: XXX,
  authority_configuration: {
    // Optional for providers that do not implement OIDC server auto-discovery via a .wellknown URL
    authorization_endpoint: 'XXX',
    token_endpoint:'XXX',
    userinfo_endpoint: 'XXX',
    revocation_endpoint: '',
    check_session_iframe: '',
    issuer: 'XXX',

  },
  service_worker_relative_url: "/OidcServiceWorker.js",
  service_worker_only: false,
  token_request_extras: {   
         client_secret: 'XXX'
  },
};
```

**Comment by guillaume-chervet** [comment]
Google will not work with silent signin (it works only if your app is inside the same domain, subdomain).
Google give an access_token valid for 1 hour and it is not possible to refresh it.

May you update to version 7.6.0 ?

![image](https://github.com/AxaFrance/oidc-client/assets/52236059/70eed081-97de-42c9-832b-529865b56cc8)

**Comment by antosimi** [comment]
Sorry for the confusion  @guillaume-chervet , you asked the browser and I am using google chrome, but the app i am doing the oauth2 login is a different one(will keep it privately). The behavior is like this : i am using this library in react to redirect and get a oidc token, after i get id token i call a backend endpoint which returns a jwt token .
I found a kind of solution but not sure: 
1- if i had nothing in my config that mentions silent, it will automatically give session expired after getting back to my app from redirect.
2- if i had silent_redirect_uri:
  window.location.origin + "/authentication/silent-callback",  -- even though i do not have anything for the silent-callback, it waited for some more seconds till it finally gets session expired.
3. - i took step 2 to next step and changing timeout to a big number : silent_login_timeout:120000000, not it takes many hours and counting.

But i am not confortable with my solution, because not sure the silent is doing.

**Comment by antosimi** [comment]
Also @guillaume-chervet I tried to update to latest version 7.6.0 but it keeps reloading:
![image](https://github.com/AxaFrance/oidc-client/assets/44970315/6f166318-5f75-4cab-af36-5876b7a62844)

![image](https://github.com/AxaFrance/oidc-client/assets/44970315/affe4f81-e975-4f42-a9ae-88300c271d8f)

**Comment by antosimi** [comment]
Also when i upgraded to latest version 7.6.0, I had to copy paste the serveice worker and trusted domains from github, because by default npm install doar not provide those and I hanged the version in service worker.
![image](https://github.com/AxaFrance/oidc-client/assets/44970315/a75bbfd8-19ea-436c-8c78-089ea4daa5a4)

Maybe when pushing, change the document service worker version, or mention in documentation

**Comment by guillaume-chervet** [comment]
Hi @antosimi , for the service worker. The mode of copy have change. Look at the documentation.

Do you use refreshToken ?  If yes, scope offline_access should be set.

**Comment by antosimi** [comment]
Thx, I've read the documentation and added the newest version of service worker, but I still get session expired and I think is from this:
![image](https://github.com/AxaFrance/oidc-client/assets/44970315/418f5c78-2e66-4d11-855f-e84e050cdf2d)

**Comment by guillaume-chervet** [comment]
Hi @antosimi , did you try to add the offline_access scope?
And comment silent sign url from ypur configuration?

**Comment by antosimi** [comment]
I do not use refresh token, I just want to get the id token, which I do, change with backend the token for jwt and then depend only for jwt token. Don;t need the service worker anymore, once i got my first token.

**Comment by guillaume-chervet** [comment]
For silent signin,  did you match all condition explained in FAQ ?

https://github.com/AxaFrance/oidc-client/blob/main/FAQ.md#faq-frequently-asked-questions

Do you know you accessToken lifetime? 
Did you tried to disable serviceworker?
If you activate logs what reason of expiration do you have?

**Comment by antosimi** [comment]
@guillaume-chervet  the silent signin was not properly used in my case that's why I said that is no solution for me. The token lifetime is not very long, but I like the idea of disabling the service worker after i got my token_id, but not sure how to do it(codewise). If you have a suggestion will be much appreciated.

**Comment by guillaume-chervet** [comment]
hi @antosimi ,

Did you try to add

`
{
   silent_redirect_uri: window.location.origin + '/authentication/silent-callback',
}
`

inside your configuration ?

**Comment by antosimi** [comment]
**SOLVED** I solved my problem with fast timeout by adding : 
```
silent_redirect_uri:
  window.location.origin + "/authentication/silent-callback",

 silent_login_timeout:604800000,
```
This made my app to not get timeout, untill my JWT token expires.
