### ISSUE TITLE
Multiple Authentication Example

### ISSUE THREAD

**Issue by nicolasiscoding** [AxaFrance/oidc-client#1153]
Hi, 

In the Readme it states that there is support for multiple providers. Is there an easy way to showcase this or a quick example? I happen to be basing my code off the NextJS example but it shouldn't matter the example

**Comment by guillaume-chervet** [comment]
Hi @nicolasiscoding , thank you for your issue.

React demo give a code example : https://github.com/AxaFrance/oidc-client/blob/main/examples/react-oidc-demo/src/MultiAuth.tsx

The only thnig to do is to inject a configurationName to each component. 1auth = 1 configurationName.

**Comment by guillaume-chervet** [comment]
Hi @nicolasiscoding , did you succed to use it?
May we close your issue?

**Comment by nicolasiscoding** [comment]
@guillaume-chervet you may close the issue. I was trying to use this with SalesForce because it supports PKCE, but kept running into CORs issues on the SalesForce side. I ended up using an Auth Code Flow initiated by the backend.

**Comment by guillaume-chervet** [comment]
Thank you very much @nicolasiscoding for your feedback ! I close the issue.
