### ISSUE TITLE
OIDC client service worker browser version detection does not work as expected in Android Web View

### ISSUE THREAD

**Issue by patrickkferguson** [AxaFrance/oidc-client#1167]
### Issue and Steps to Reproduce

The [getBrowser function](https://github.com/AxaFrance/oidc-client/blob/main/packages/oidc-client/src/initWorker.ts#L76) in the OIDC client service worker initialisation returns an incorrect version when processing an Android WebView user agent string.

For example, parsing the user agent string
```
Mozilla/5.0 (Linux; Android 11; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.117 Mobile Safari/537.36
```
Will return
```
{
    name: 'chrome',
    version: 4,
}
```
And the service worker will not initialise.

#### Expected
The code should detect the browser version based on the Chrome version and initialise the service worker if it is greater than or equal to 70.

#### Actual
To code detects a browser version which is not representative of the installed Chrome version.

**Comment by guillaume-chervet** [comment]
Hi @patrickkferguson , I am not fan of this part of the library.
I do not know what to do bu i think i will give the full control to the developper.

I am in holiday this week. 

Thank you forbyour issue.

**Comment by guillaume-chervet** [comment]
hi @patrickkferguson, version 7.9.0-alpha.1110 implement a new configuration property.

service_worker_activate : () => true

will do the job.

**Comment by guillaume-chervet** [comment]
Hi @patrickkferguson , I close the issue. You can now take the control for that on android. Feel free to reopen it or respond if you need it.
