### ISSUE TITLE
Service Worker intercepting some API calls and changing IdToken to AccessToken

### ISSUE THREAD

**Issue by pr0xyMity** [AxaFrance/oidc-client#1168]
### Versions
7.7.2

### Screenshots
-------
**First please take a look here for one request we are doing "two" but the one is from service worker**

![image](https://github.com/AxaFrance/oidc-client/assets/18540580/9f1759be-38e0-4fdc-8eba-a0caece95e31)

-------
**The first request (without the cog icon) is done with the right id_token (I've tested it on postman an it works)**
You can also see that the error code 401 has info inside the brackets (401 Unauthorized (from service worker))

![image](https://github.com/AxaFrance/oidc-client/assets/18540580/9e0cebb8-8a00-4d0a-9760-4fe3baf81620)
![image](https://github.com/AxaFrance/oidc-client/assets/18540580/51742962-bfc5-4f8a-8da3-1608c99ed481)

-------
**The second one, the service worker one has changed the id_token for access_token. Don't know why...**

![image](https://github.com/AxaFrance/oidc-client/assets/18540580/8866469f-6998-4361-93d2-e9bb79f1bdea)
-------
#### Expected
The app asks the proper API endpoint with valid Bearer Token (Bearer + IdToken) and returns what postman is returning.

#### Actual
It seems like the service worker is intercepting some of the requests and changing the Bearer token from:
`Bearer + Id_token` to `Bearer + Access_token`

### Additional Details
My configuration:
```
const configuration: OidcConfiguration = {
  authority: window.AUTH.AUTHORITY,
  client_id: window.AUTH.CLIENT_ID,
  redirect_uri: window.location.origin + "/authentication/callback",
  silent_redirect_uri:
    window.location.origin + "/authentication/silent-callback",
  scope: `openid profile email offline_access ${userMetadataScope} ${projectRolesScope} ${audienceScope}`, // offline_access scope allow your client to retrieve the refresh_token
  service_worker_relative_url: "/OidcServiceWorker.js", // just comment that line to disable service worker mode
  service_worker_only: false,
  demonstrating_proof_of_possession: false, // demonstrating proof of possession will work only if access_token is accessible from the client (This is because WebCrypto API is not available inside a Service Worker)
};
```

**Comment by guillaume-chervet** [comment]
Hi @pr0xyMity ,thank you for your issue.
I am interrested to know of what did you do to resolve it?

**Comment by pr0xyMity** [comment]
Hi @guillaume-chervet 
this was caused by one **missing** middleware in on of the api services. All accepted accessTokens but only one was missing the middleware to handle this. 

This wasn't a library issue ;)
Enjoy your vacation!
