### ISSUE TITLE
Logout/End Session not workign correctly with AWS Cognito Hosted UI

### ISSUE THREAD

**Issue by dhaub-exelixis** [AxaFrance/oidc-client#1173]
### Issue and Steps to Reproduce

When using AWS Cognito as an OIDC provider, the way Cognito handles ending sessions and logging out doesn't quite work for this package. Since Cognito doesn't provide a dedicated `/end-session` endpoint, it is necessary to use the `/logout` endpoint instead. Documentation for this endpoint can be found here: [logout](https://docs.aws.amazon.com/cognito/latest/developerguide/logout-endpoint.html)

The full list of provided endpoints can be found here: [Hosted UI](https://docs.aws.amazon.com/cognito/latest/developerguide/hosted-UI-endpoints.html) and [federation](https://docs.aws.amazon.com/cognito/latest/developerguide/federation-endpoints.html)

### Versions

7.7.3

#### Expected

When calling `logout()`, the session is ended and the user is sent to the desired logout callback location

#### Actual

The tokens are removed from storage, but not revoked by Cognito and the user is returned to the same page from which they logged out. If that page is protected, the user is signed right back in

### Additional Details

I believe this can be worked around by adding another option to the `authority_configuration` part of the config; a `logout_endpoint` that is handled [here](https://github.com/AxaFrance/oidc-client/blob/b4cee5aec8365ba2b000742001c717f1d543011b/packages/oidc-client/src/logout.ts#L78) during the logout function call. In order for this to not be a breaking change, it can be handled as an `else` condition in the `if/else` block linked earlier.

I'll see if I can get this working locally and make a PR :)

**Comment by dhaub-exelixis** [comment]
Upon further inspection of the code, you can get around this by passing in the `extras` parameter to the `logout()` function and if `end_session_endpoint` is set to cognito's `/logout` endpoint.

 ```
logout(null, {
    client_id: <client ID>
    logout_uri: `${window.location.origin}/<logout path>`,
  });
```

works as expected

**Comment by guillaume-chervet** [comment]
Thank you @dhaub-exelixis for the feedback!
