### ISSUE TITLE
Need to call for oidc info in services and reactrouter loaders where hooks are not going to work. 

### ISSUE THREAD

**Issue by getsetbro** [AxaFrance/oidc-client#1174]
I have an app that is using the react-router 6.4 which calls apis in the loaders before it runs the components. Their loader functions call the apis before the auth calls are done. I need a way to only fire the api calls if the auth info has been received. Thanks

Versions

Screenshots

Expected

Actual

Additional Details

Installed packages:
"@axa-fr/react-oidc": "^7.7.3",
"react": "^18.2.0",
"react-dom": "^18.2.0",
"react-redux": "^8.1.2",
"react-router-dom": "^6.15.0",
"typescript": "^5.0.2",
"vite": "^4.4.5"

**Comment by guillaume-chervet** [comment]
Hi @getsetbro , thank you for your issue.

Can you set up OidcProvider at the top level of your application ? 
This should resolve your problem.

**Comment by guillaume-chervet** [comment]
Hi @getsetbro , can you use HOC to inject the oidc fetch?

Else you can access oidc fetch via oidc-client api.

**Comment by getsetbro** [comment]
How do i do it with the oidc-client api. Can you point me to the steps?
Thanks

**Comment by guillaume-chervet** [comment]
Hi @getsetbro , 
The code is inside react oidc library and not usable like it.
I have to make an evolution to make it available to oidc-client and suitable for your use case.


https://github.com/AxaFrance/oidc-client/blob/main/packages/react-oidc/src/FetchToken.tsx

I think i will be able to do this next monday.

**Comment by getsetbro** [comment]
That we be very very helpful thank you!! @guillaume-chervet

**Comment by getsetbro** [comment]
You mentioned this idea “use HOC to inject the oidc fetch?” How would that work? I have to kick off the router from the main.tsx before any component is created or else any changes will restart the router and if the router is restarted than all the api calls in the loader are called again.

**Comment by guillaume-chervet** [comment]
hi @getsetbro ,

latest version integrate it.

It should be usable like bellow

```js
import {OidcClient} from '@axa-fr/oidc-client'
export const configuration = {
  client_id: 'interactive.public.short',
  redirect_uri: window.location.origin + '/#/authentication/callback',
  silent_redirect_uri: window.location.origin + '/#/authentication/silent-callback',
  scope: 'openid profile email api offline_access',
  authority: 'https://demo.duendesoftware.com',
  service_worker_relative_url: '/OidcServiceWorker.js',
  service_worker_only: false,
  demonstrating_proof_of_possession: false, // demonstrating proof of possession will work only if access_token is accessible from the client (This is because WebCrypto API is not available inside a Service Worker)
};
const oidcClient = OidcClient.getOrCreate()(configuration);

// Use the fetch bellow to inject access_token and DPOP tokens automatically
const oidcFetch = oidcClient.fetchWithTokens(fetch);

```

It is the library used behing react-oidc.

**Comment by getsetbro** [comment]
Hello. How do I configure it to use the idToken instead of access token? Also my api does not accept the Bearer word in front of it.

**Comment by guillaume-chervet** [comment]
hi @getsetbro ,

How do you need to send your idToken ? in Authorization HTTP headers field ?
Do you know that it is a very bad praticite to use idToken instead of accessToken?

**Comment by getsetbro** [comment]
Thanks. I’ll let the team know

**Comment by guillaume-chervet** [comment]
Event if you are sending idTokens we can find solution in order to make it works with service worker. Without service worker you just need to add idToken in a classic fetch.

**Comment by getsetbro** [comment]
Tanks
