### ISSUE TITLE
Service Worker scope

### ISSUE THREAD

**Issue by BorisTB** [AxaFrance/oidc-client#1181]
### Issue and Steps to Reproduce

I need to set service worker's scope, as my app is running on sub-path (example.com/differentapp/myapp), but currently there's no way to pass options to serviceWorker.register method

https://github.com/AxaFrance/oidc-client/blob/24135038510ada4b9eecffae1494693ef9347a07/packages/oidc-client/src/initWorker.ts#L75

### Additional Details

- Installed packages:

**Comment by guillaume-chervet** [comment]
hi @BorisTB , 
Thank you for you issue !
I will add it as quicky as I can to help you.

**Comment by guillaume-chervet** [comment]
Hi @BorisTB ,

very sorry for the delay, I have added https://github.com/AxaFrance/oidc-client/commit/49c3d5e5487d714ccd97272e37fc34f2a7bd0ff6 in the lastest version. It allow you to take the full control over the registration.

**Comment by BorisTB** [comment]
Thank you! I can't even describe how much you just helped me
