### ISSUE TITLE
Error thrown on logout for user not assigned to the app

### ISSUE THREAD

**Issue by grpawel** [AxaFrance/oidc-client#1182]
Hi,
I found a small bug:
When I log in with a user not assigned to the application and then try to logout, oidc-client logs two warnings on the console:

> logoutAsync: error when revoking tokens, if the error persist, you ay configure property logout_tokens_to_invalidate from configuration to avoid this error
>
> TypeError: Cannot read properties of null (reading 'accessToken')

The reason is that Okta doesn't return any tokens for the user, only an error `User is not assigned to the client application.`

The error is thrown in this line:
https://github.com/AxaFrance/oidc-client/blob/24135038510ada4b9eecffae1494693ef9347a07/packages/oidc-client/src/logout.ts#L49
`oidc.tokens` is null. Most likely it should be handled like `idToken` in line 44:
```
const accessToken = oidc.tokens ? oidc.tokens.accessToken : '';
```

**Comment by guillaume-chervet** [comment]
hi @grpawel ,

Thank you very much for you issue !
I will fix it as quickly as I can !

**Comment by guillaume-chervet** [comment]
Hi @grpawel , version 7.9.1 should fix your issue.

**Comment by grpawel** [comment]
Thank you Guillaume! I've tested the latest version and the issue is fixed.
