### ISSUE TITLE
Normalize URLs in OidcServiceWorker.js

### ISSUE THREAD

**Issue by meesvandongen** [AxaFrance/oidc-client#1189]
### Issue and Steps to Reproduce

Currently URLs in comparisons are not normalized, which can cause certains calls to fail; e.g. 

```ts
url === oidcServerConfiguration.tokenEndpoint
```

this will return false if one URL contains a port and the other does not (some IDPs include a port).

I can create a merge request if needed; we could use a package `normalize-url` to solve it, or implement only a subset of the rules.

### Versions

`@axa-fr/oidc-client-service-worker@7.7.3`

**Comment by guillaume-chervet** [comment]
Hi @meesvandongen , thank you very much for your issue.
Do you have a full sample of rigth and l'est equality side?

It would be a please to accept your pullrequest. 

I would like to not include package dependency. I prefer to add clean unit test and resolve your case.
I am trying to remove all depency at all for many reason (security are part of).

**Comment by meesvandongen** [comment]
An example would be `https://idp.com/token === https://idp.com:443/token`

**Comment by meesvandongen** [comment]
@guillaume-chervet perhaps this can be reopened. I mistakenly thought this was the only place where such a check was made, but that is not correct. It is also made in `getCurrentDatabasesTokenEndpoint` and perhaps other places. I still believe it is a good idea to normalize the URL: the URLs received by the `fetch` event listener are also not exactly equal to the URLs provided to a fetch request:

![image](https://github.com/AxaFrance/oidc-client/assets/35409045/b75d3fc5-da59-4106-ab32-336b05fdcd2d)

with the following code:

```ts
_self.addEventListener("fetch", handleFetch);
const handleFetch = async (event) => {
  const originalRequest = event.request;
  const url = originalRequest.url;
  console.log(url);
```

Anyway, if we want to proceed with this it must be decided where the URLs should be normalized; I would suggest as early as possible, so right after handleFetch, as well as right after obtaining the values from the openid configuration endpoint. But, the openid configuration is retrieved in the client package, so that would result in potential code duplication. Other possibility is right before the configuration is saved to a variable in the service worker; then the client package will not have to change, but there may be potential differences in behaviour between the two modes. What do you think?

**Comment by guillaume-chervet** [comment]
hi @meesvandongen , do a proposition with a code PullRequest.
I'am lacking of time. I prefer something not perfect that work than nothing :)

**Comment by guillaume-chervet** [comment]
Thank you so much to make some feedback and help!
