### ISSUE TITLE
Implementing Implicit flow fails (id_token) at react oidc

### ISSUE THREAD

**Issue by desmati** [AxaFrance/oidc-client#1195]
### Issue and Steps to Reproduce

I tried to update the react-oidc-demo to use Implicit flow but I could not do that. The response_type will be send "code" in all cases.

First issue is about using a http endpoint which will fail with this message: 
```
OidcServiceWorker.js:31  Uncaught Error: Domain null is not trusted, please add domain in OidcTrustedDomains.js
    at checkDomain (OidcServiceWorker.js:31:11)
    at OidcServiceWorker.js:513:11
    at Array.forEach (<anonymous>)
    at handleMessage (OidcServiceWorker.js:512:11)
checkDomain @ OidcServiceWorker.js:31
(anonymous) @ OidcServiceWorker.js:513
handleMessage @ OidcServiceWorker.js:512
```

I'm using docker and am using 'host.docker.internal' as my docker network domain name.

Anyway, going back to the main issue, I managed to use https and here is the url which contain response_type.

`https://localhost:5105/connect/authorize?client_id=react&redirect_uri=http%3A%2F%2Flocalhost%3A5173%2Fauthentication%2Fcallback&scope=openid%20profile%20email%20api%20offline_access&response_type=code&youhou_demo=youhou&state=tODdBr4b5VvqrQjR&nonce=HadatUNQ4C0s&code_challenge=8b6g3eS42plob_rQHSKFlBl0YgalR-GF6t7Z9H2LiWk&code_challenge_method=S256
`

Here is my oidc config:

`
{
    "issuer": "null",
    "jwks_uri": "https://localhost:5105/.well-known/openid-configuration/jwks",
    "authorization_endpoint": "https://localhost:5105/connect/authorize",
    "token_endpoint": "https://localhost:5105/connect/token",
    "userinfo_endpoint": "https://localhost:5105/connect/userinfo",
    "end_session_endpoint": "https://localhost:5105/connect/endsession",
    "check_session_iframe": "https://localhost:5105/connect/checksession",
    "revocation_endpoint": "https://localhost:5105/connect/revocation",
    "introspection_endpoint": "https://localhost:5105/connect/introspect",
    "device_authorization_endpoint": "https://localhost:5105/connect/deviceauthorization",
    "backchannel_authentication_endpoint": "https://localhost:5105/connect/ciba",
    "frontchannel_logout_supported": true,
    "frontchannel_logout_session_supported": true,
    "backchannel_logout_supported": true,
    "backchannel_logout_session_supported": true,
    "scopes_supported": [
        "openid",
        "profile",
        "orders",
        "basket",
        "mobileshoppingagg",
        "webshoppingagg",
        "orders.signalrhub",
        "webhooks",
        "offline_access"
    ],
    "claims_supported": [
        "sub",
        "name",
        "family_name",
        "given_name",
        "middle_name",
        "nickname",
        "preferred_username",
        "profile",
        "picture",
        "website",
        "gender",
        "birthdate",
        "zoneinfo",
        "locale",
        "updated_at"
    ],
    "grant_types_supported": [
        "authorization_code",
        "client_credentials",
        "refresh_token",
        "implicit",
        "password",
        "urn:ietf:params:oauth:grant-type:device_code",
        "urn:openid:params:grant-type:ciba"
    ],
    "response_types_supported": [
        "code",
        "token",
        "id_token",
        "id_token token",
        "code id_token",
        "code token",
        "code id_token token"
    ],
    "response_modes_supported": [
        "form_post",
        "query",
        "fragment"
    ],
    "token_endpoint_auth_methods_supported": [
        "client_secret_basic",
        "client_secret_post"
    ],
    "id_token_signing_alg_values_supported": [
        "RS256"
    ],
    "subject_types_supported": [
        "public"
    ],
    "code_challenge_methods_supported": [
        "plain",
        "S256"
    ],
    "request_parameter_supported": true,
    "request_object_signing_alg_values_supported": [
        "RS256",
        "RS384",
        "RS512",
        "PS256",
        "PS384",
        "PS512",
        "ES256",
        "ES384",
        "ES512",
        "HS256",
        "HS384",
        "HS512"
    ],
    "authorization_response_iss_parameter_supported": true,
    "backchannel_token_delivery_modes_supported": [
        "poll"
    ],
    "backchannel_user_code_parameter_supported": true
}
`

And this is the error:
`Error
Sorry, there was an error : unauthorized_client
Unknown client or client not enabled
Request Id: 0HMV6GJR8E0A6:00000001`

### Versions

Same as the example project from the main branch

#### Expected

To send the response_type as 'id_token token' 

#### Actual

response_type is 'code'

### Additional Details

- Installed packages:
- 
Same as the example project from the main branch

**Comment by desmati** [comment]
Additionally, here is my IdentityServer configuration:

`new Client
                {
                    ClientId = "react",
                    ClientName = "eShop React OpenId Client",
                    AllowedGrantTypes = GrantTypes.Implicit,
                    AllowAccessTokensViaBrowser = true,
                    RequireConsent = false,
                    RedirectUris = { $"https://localhost:5173/authentication/callback",$"http://localhost:5173/authentication/callback" },
                    PostLogoutRedirectUris = { "https://localhost:5173/","http://localhost:5173/" },
                    AllowedCorsOrigins = { "https://localhost:5173/","http://localhost:5173/" },
                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        "orders",
                        "basket",
                        "webshoppingagg",
                        "orders.signalrhub",
                        "webhooks"
                    },
                },`

**Comment by guillaume-chervet** [comment]
Hi @desmati ,

We do not support implicit flow because it is too much unsecure.
If you can use : code grand flow with pcke mode it is more secure.

And if you can, activate DPOP mode. Tokens will be unsable outside of browser context.
