### ISSUE TITLE
Invalid Token in demo

### ISSUE THREAD

**Issue by Djay77** [AxaFrance/oidc-client#1199]
### Issue and Steps to Reproduce

Hello,

I've tried the next-js demo from your repo and also the wrapper in a new nextjs application (with the same configuration as the demo) and I have the call to "https://demo.duendesoftware.com/connect/token" running in a loop because the token is invalid.
(TOKENS_INVALID)

Is this normal ?

Thanks in advance

### Versions
"@axa-fr/react-oidc": "7.9.2",

#### Actual
<img width="1494" alt="image" src="https://github.com/AxaFrance/oidc-client/assets/3582550/03384390-3296-42e0-89c4-a3ec101819c1">

### Additional Details

- Installed packages:

**Comment by guillaume-chervet** [comment]
Hi @Djay77 , thank you for the feedback i check it rigth now!

**Comment by guillaume-chervet** [comment]
hi @Djay77 ,

I do not reproduce that. Do you have the message why the token is invalid?
![image](https://github.com/AxaFrance/oidc-client/assets/52236059/b70dbe5f-2b0f-4202-bba7-5e4677c5c74f)

**Comment by guillaume-chervet** [comment]
Hi @Djay77 , i close the issue.
Feel free to repon it if you need it.
