### ISSUE TITLE
sessionStorage is not defined error in 7.13.0 or later

### ISSUE THREAD

**Issue by pavankjadda** [AxaFrance/oidc-client#1238]
### Issue and Steps to Reproduce

After upgrading from **7.12.12** to **7.13.6** I see error
```
ReferenceError: sessionStorage is not defined

```

### Versions
**Old**: 7.12.12
**New**: 7.13.6
### Screenshots
<img width="1406" alt="Screenshot 2023-12-10 at 10 12 34 AM" src="https://github.com/AxaFrance/oidc-client/assets/17564080/0f48ecac-f35d-45c2-a68d-09da97718141">

#### Expected
Authentication should work as expected

#### Actual
The build fails and shows error `ReferenceError: sessionStorage is not defined`

### Additional Details
I think this is caused by change introduced in https://github.com/AxaFrance/oidc-client/releases/tag/v7.13.1

**Comment by guillaume-chervet** [comment]
Thank you @pavankjadda for your feedback i will make my best to fix it today!

**Comment by pavankjadda** [comment]
@guillaume-chervet BTW, is it possible to use localStorage with Next.JS?

**Comment by pavankjadda** [comment]
> Hi @pavankjadda , sorry i did get enough time to fix it yesterday.
> 
> Yes of course you can. Just remeber that oidc client work at client side. User informations won't be accessible at server side. For example for server side rendering.

When I try to `localStorage`, I see below error

<img width="968" alt="Screenshot 2023-12-12 at 11 35 15 AM" src="https://github.com/AxaFrance/oidc-client/assets/17564080/18cd3478-f85a-4bc1-81fc-9f5d7db7a18f">

**Comment by guillaume-chervet** [comment]
Oh thank you @pavankjadda , i think I have an evolution to do. Window is undefined during nextjs first rendering.
