### ISSUE TITLE
Couldnt find a feature flag to disable the auth by single switch

### ISSUE THREAD

**Issue by pgangwani** [AxaFrance/oidc-client#1239]
### Issue and Steps to Reproduce
I read the whole doc but couldnt find a single switch to disable to auth completely in case there is environemnt specific thing I require say in dev/local , I dont want any authentication/authorization , is there  a way to disable fully ? However production work like as intended to be enabled 

### Versions
all
### Screenshots
NA
#### Expected
Single kill switch to disable/enable all provider & secure & service worker with a flag. By default flag should be enabled
#### Actual
Didnt find such flag in configuration
### Additional Details

- Installed packages:

**Comment by pgangwani** [comment]
@guillaume-chervet : Would you be able to answer or help if this feature is available ?

**Comment by guillaume-chervet** [comment]
Hi @pgangwani , very sorry for the delay.
In version 1, 2 and 3 this feature was present. But we decide to remove it, because nowaday it is easy to configure à local OIDC provider in dev environment.  For example by using keycloack.

**Comment by pgangwani** [comment]
> Hi @pgangwani , very sorry for the delay. In version 1, 2 and 3 this feature was present. But we decide to remove it, because nowaday it is easy to configure à local OIDC provider in dev environment. For example by using keycloack.

Thanks @guillaume-chervet , I would appreciate if you can share the example of any keycloack. 

Additionally is there any channel/discord/slack where I can report the problem  related to service worker pattern, may be missing in config?

**Comment by pgangwani** [comment]
got it thanks
