### ISSUE TITLE
"Uncaught (in promise) TypeError: c is null" when device = iPad (iPadOS 14.7.1) is set in Firefox Dev Tools

### ISSUE THREAD

**Issue by magicxor** [AxaFrance/oidc-client#1242]
### Issue and Steps to Reproduce

1) Create any project using `"@axa-fr/react-oidc": "^7.13.6"`
2) Launch **Firefox 120.0.1** (64-bit) on Windows
3) Open **Dev Tools -> Responsive Design Mode -> Set device = iPad (iPadOS 14.7.1)**
4) Go to any route wrapped with `<OidcSecure>`
5) You will get an error:

```
Error authentication

An error occurred during authentication.
```

```
Uncaught (in promise) TypeError: c is null
    fs index.js:1026
    _s index.js:1057
    E index.js:313
    rs index.js:804
    rs index.js:823
    loginAsync index.js:1205
    loginAsync index.js:1413
    login index.js:838
    SignInWaitScreen SignInWaitScreen.tsx:17
    React 13
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    js scheduler.development.js:571
    js scheduler.development.js:633
    __require2 chunk-GFT2G5UO.js:18
    js index.js:6
    __require2 chunk-GFT2G5UO.js:18
    React 2
    __require2 chunk-GFT2G5UO.js:18
    js React
    __require2 chunk-GFT2G5UO.js:18
    js React
    __require2 chunk-GFT2G5UO.js:18
    <anonymous> react-dom_client.js:38
```

![image](https://github.com/AxaFrance/oidc-client/assets/8275793/91f08760-77c5-4c4e-9a3c-c69d4838f217)

Source code:

https://github.com/AxaFrance/oidc-client/blob/9f1f7f684a6b344f59221caf3e3a14faef73a6bc/packages/oidc-client/src/initWorkerOption.ts#L71

### Versions

@axa-fr/oidc-client 7.13.6
@axa-fr/react-oidc 7.13.6

### Screenshots

![image](https://github.com/AxaFrance/oidc-client/assets/8275793/7de44aa8-51d6-4cd0-8cfc-bff26ab93c0c)

#### Expected

There is no exception; the user is redirected to auth

#### Actual

There is an exception `Uncaught (in promise) TypeError: c is null`; the user sees `Error authentication An error occurred during authentication.`

### Additional Details

- Installed packages:

`"@axa-fr/react-oidc": "^7.13.6"`

full list:

```
  "dependencies": {
    "@axa-fr/react-oidc": "^7.13.6",
    "@emotion/react": "^11.11.1",
    "@emotion/styled": "^11.11.0",
    "@framit/meta-pixel": "^1.0.0",
    "@js-joda/core": "^5.6.1",
    "@mui/icons-material": "^5.14.19",
    "@mui/lab": "^5.0.0-alpha.154",
    "@mui/material": "^5.14.19",
    "@mui/x-data-grid": "^6.18.2",
    "@redux-devtools/extension": "^3.2.6",
    "@reduxjs/toolkit": "^1.9.7",
    "@stripe/react-stripe-js": "^2.4.0",
    "@stripe/stripe-js": "^2.2.0",
    "clsx": "^2.0.0",
    "content-disposition-header": "^0.6.0",
    "deep-clone": "^3.0.3",
    "file-saver": "^2.0.5",
    "i18next": "^23.7.7",
    "i18next-http-backend": "^2.4.2",
    "ismobilejs": "^1.1.1",
    "json-stable-stringify": "^1.1.0",
    "mui-datatables": "^4.3.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-country-flag": "^3.1.0",
    "react-dom": "^18.2.0",
    "react-dropzone": "^14.2.3",
    "react-ga4": "^2.1.0",
    "react-helmet": "^6.1.0",
    "react-i18next": "^13.5.0",
    "react-phone-input-2": "^2.15.1",
    "react-redux": "^8.1.3",
    "react-router-dom": "^6.20.0",
    "store": "^2.0.12",
    "ts-simple-nameof": "^1.3.1",
    "tsdef": "^0.0.14",
    "uuid": "^9.0.1"
  },
  "devDependencies": {
    "@types/file-saver": "^2.0.7",
    "@types/jest": "^29.5.10",
    "@types/json-stable-stringify": "^1.0.36",
    "@types/node": "^20.10.1",
    "@types/react": "^18.2.39",
    "@types/react-dom": "^18.2.17",
    "@types/react-helmet": "^6.1.9",
    "@types/react-redux": "^7.1.31",
    "@types/store": "^2.0.5",
    "@types/uuid": "^9.0.7",
    "@typescript-eslint/eslint-plugin": "^6.13.1",
    "@typescript-eslint/parser": "^6.13.1",
    "@vitejs/plugin-react-swc": "^3.5.0",
    "cross-env": "^7.0.3",
    "eslint": "^8.54.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-airbnb-typescript": "^17.1.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-import": "^2.29.0",
    "eslint-plugin-prettier": "^5.0.1",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.4",
    "prettier": "^3.1.0",
    "typescript": "^5.3.2",
    "vite": "^5.0.4",
    "vite-plugin-mkcert": "^1.17.1"
  },
  "overrides": {
    "mui-datatables": {
      "react-virtualized": "9.22.4"
    }
  },
```

**Comment by magicxor** [comment]
I think that we need to have a fallback for osVersionArray in case if `/OS (\d+)_(\d+)_?(\d+)?/.exec(nVer)` returns no results.

It expects something like `Mozilla/5.0 (iPhone; CPU iPhone OS 17_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Mobile/15E148 Safari/604.1` but there is no guarantee that Apple won't change it in future releases.

**Comment by guillaume-chervet** [comment]
I @magicxor thank you for your feedback.
Yes this part need a fallback.

I think in a future release version i will remove these behavior by default and include functions in another package injectable from oidc configuration.
So développer will be able to manage properly all their use case. User agent is not fiable.

**Comment by guillaume-chervet** [comment]
Hi @magicxor latest version manage the case. It should just activate service worker in that case.
There is a property in the configuration to take the control on the service worker activation.

**Comment by magicxor** [comment]
Hi. I've tested with the latest version, and I'm happy to confirm that the issue is indeed fixed now. Thank you so much. Have a prosperous new year!
