### ISSUE TITLE
Always seeing "Error authentication" in local during first load of the site

### ISSUE THREAD

**Issue by pavankjadda** [AxaFrance/oidc-client#1251]
### Issue and Steps to Reproduce
In my next.js project, I use `@axa-fr/react-oidc` to integrate with OIDC server. In my local setup, when I first open any webpage, it redirects me to login page and after successful login, it shows "Error authentication" message. I do not see this error when deployed to DEV or PROD 

### Versions
7.13.12

### Screenshots
<img width="1084" alt="Screenshot 2023-12-28 at 7 03 09 PM" src="https://github.com/AxaFrance/oidc-client/assets/17564080/ad71a879-169a-4d90-bcf8-57bded79b97e">

#### Expected
The redirection should work as expected

#### Actual
Says "State not valid" in dev tools and "Error authentication" in UI

**Comment by pavankjadda** [comment]
After debugging for hours, I figured out the issue. I have custom 404 page that decodes the if URL is encoded and redirects to decoded version. This is designed for application URLs. But it also applying OIDC callback, hence the error. Added exception for OIDC URLs and it fixed the issue.

@guillaume-chervet question. The URL is being coded after authentication. How can we prevent this? For example

1. User requests url `/employee?id=1001`
2. The library redirects to OIDC server login page and users enters credentials
3. User is being redirected to `/employee%3Fid%3D1001`


How can I prevent step 3? Is this being done by React Router in the library?

**Comment by guillaume-chervet** [comment]
Hi @pavankjadda , very sorry for the delay.
Did you solve your problem? How did you solve it?

**Comment by pavankjadda** [comment]
> After debugging for hours, I figured out the issue. I have custom 404 page that decodes the if URL is encoded and redirects to decoded version. This is designed for application URLs. But it also applying OIDC callback, hence the error. Added exception for OIDC URLs and it fixed the issue.

After debugging for hours, I figured out the issue. I have custom 404 page that decodes the if URL is encoded and redirects to decoded version. This is designed for application URLs. But it also applying OIDC callback, hence the error. Added exception for OIDC URLs and it fixed the issue.
