### ISSUE TITLE
Uncaught SyntaxError: "undefined" is not valid JSON

### ISSUE THREAD

**Issue by gitawego** [AxaFrance/oidc-client#1257]
### Issue and Steps to Reproduce

when calling method `getLoginParams` in file `initSession.ts`, if there is no param set in localStorage, then it throws error 

```
Uncaught SyntaxError: "undefined" is not valid JSON
```

It happens very frequently. 

based on the code, `JSON.parse` can't parse the `undefined` value, if `dataString` is undefined, then oidc can't initialize the session.

```ts
const getLoginParams = () => {
        const dataString = storage[`oidc.login.${configurationName}`];
        if (!getLoginParamsCache[configurationName]) {
            getLoginParamsCache[configurationName] = JSON.parse(dataString);
        }
        return getLoginParamsCache[configurationName];
    };
```

maybe we should add a default value to dataString, like

```ts
const dataString = storage[`oidc.login.${configurationName}`] || 'null';
```

### Versions

all

**Comment by guillaume-chervet** [comment]
Hi @gitawego , 
Thank you for your issue.
Which version of the library are you using ?
Do you have a sample (ofuscated) of your configuration ?

I'am searching from a long time why storage can be null. It never set to null in the code and values are required to refresh tokens correctly.

**Comment by gitawego** [comment]
I put `null` is only to make JSON.parse works, because undefined can't be parsed. 

in this line of code: https://github.com/AxaFrance/oidc-client/blob/main/packages/oidc-client/src/initSession.ts#L66
```js
const dataString = storage[`oidc.login.${configurationName}`];
```

`dataString` could be `undefined`,

and when parsed at line 68: https://github.com/AxaFrance/oidc-client/blob/main/packages/oidc-client/src/initSession.ts#L68

```js
getLoginParamsCache[configurationName] = JSON.parse(dataString);
```

if `dataString` is undefined, it throws error, because `JSON.parse` can't parse undefined.


```js
JSON.parse(JSON.stringify(undefined)) // throw Uncaught SyntaxError: "undefined" is not valid JSON
JSON.parse(undefined) //Uncaught SyntaxError: "undefined" is not valid JSON
JSON.parse(null) // return value null
JSON.parse(JSON.stringify(null)) // return value null
```

in my company, it's v7.6.0, but I compared, this part of the code is never changed.

**Comment by guillaume-chervet** [comment]
I will manage this case with a warning instead of a crash.
It would not be a problem for 90% of configurations cases.

But i Wonder how storage[`oidc.login.${configurationName}`] can be null because it is set during authentication.

**Comment by guillaume-chervet** [comment]
Do you have a sample of the stack trace of the error ?

**Comment by gitawego** [comment]
I'll try to get it tomorrow.

**Comment by Maingart** [comment]
@gitawego, hello! What was the reason?

**Comment by LeadcodeDev** [comment]
Same issue with Next application
