### ISSUE TITLE
Service Worker Ignore Path

### ISSUE THREAD

**Issue by paulbenjamin3409** [AxaFrance/oidc-client#1260]
### Issue and Steps to Reproduce

When interacting with a CubeJS server, the cubejs server sets its authorization token in the header. When the OIDC client service worker proxies the request, it replaces the authorization with the oidc token. How would I instruct the service worker to ignore that particular endpoint, ie. http://cubejs.service.com/command and not attach the oidc token?

### Versions
7.13.14

### Additional Details

- Installed packages:

**Comment by guillaume-chervet** [comment]
Hi @paulbenjamin3409 ,

TrustedDomains accept regex and also path and subpath.
You can build a regex which wont accept your specific path so tokens won"t be send to that particular endpoint.

**Comment by paulbenjamin3409** [comment]
Yup, I am dumb. Thanks.
