### ISSUE TITLE
react-oidc: useOidcFetch unnecessary console log entry "newFetch"

### ISSUE THREAD

**Issue by Ediste** [AxaFrance/oidc-client#1262]
### Issue and Steps to Reproduce

Each time useOidcFetch is used, an entry with newFetch and the corresponding route is displayed in the console. This is messy in a production system. Could this be removed or perhaps made configurable by a LogLevel?

### Versions
7.13.14

### Screenshots
![image](https://github.com/AxaFrance/oidc-client/assets/48368916/001967ae-3ed0-404c-883d-3efd131ff7cb)

#### Expected
Remove console.logs for fetches

#### Actual
Console log entry for each fetch

**Comment by guillaume-chervet** [comment]
Thank you very much @Ediste,

Fresh version 7.13.15 fix this.

**Comment by Ediste** [comment]
Thank you for the fast response and fix. The console logs are now gone in the latest version (7.13.15). Great work!

**Comment by Ediste** [comment]
Thank you for the fast response and fix. The console logs are now gone in the latest version (7.13.15). Great work!
