### ISSUE TITLE
parseJwt fails for some JWT because of wrong use of replace()

### ISSUE THREAD

**Issue by johakoch** [AxaFrance/oidc-client#1268]
### Issue and Steps to Reproduce

The parseJwt() function fails to parse some JWT (with multiple occurences of '-' or '_').
https://github.com/AxaFrance/oidc-client/blob/main/packages/oidc-client/src/parseTokens.ts#L5C76-L5C112 and https://github.com/AxaFrance/oidc-client/blob/main/packages/oidc-client-service-worker/src/utils/tokens.ts#L15C41-L15C77
```
.replace('-', '+').replace('_', '/')
```
replace() with string first param only replaces the _first_ occurence.

Use
```
.replace(/-/g, '+').replace(/_/g, '/')
```
instead.

Example:
```
claimsPart = "eyJzZXNzaW9uX3N0YXRlIjoiNzVjYzVlZDItZGYyZC00NTY5LWJmYzUtMThhOThlNjhiZTExIiwic2NvcGUiOiJvcGVuaWQgZW1haWwgcHJvZmlsZSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoixrTHosOBw6zDhyDlsI_lkI0t44Ob44Or44OYIiwicHJlZmVycmVkX3VzZXJuYW1lIjoidGVzdGluZ2NoYXJhY3RlcnNAaW52ZW50ZWRtYWlsLmNvbSIsImdpdmVuX25hbWUiOiLGtMeiw4HDrMOHIiwiZmFtaWx5X25hbWUiOiLlsI_lkI0t44Ob44Or44OYIn0"

atob(claimsPart.replace('-', '+').replace('_', '/'))
```
throws error, while
```
atob(claimsPart.replace(/-/g, '+').replace(/_/g, '/'))
```
can be decoded to
```
{"session_state":"75cc5ed2-df2d-4569-bfc5-18a98e68be11","scope":"openid email profile","email_verified":true,"name":"Æ´Ç¢Ã\u0081Ã¬Ã\u0087 å°\u008få\u0090\u008d-ã\u0083\u009bã\u0083«ã\u0083\u0098","preferred_username":"testingcharacters@inventedmail.com","given_name":"Æ´Ç¢Ã\u0081Ã¬Ã\u0087","family_name":"å°\u008få\u0090\u008d-ã\u0083\u009bã\u0083«ã\u0083\u0098"}
```

### Versions

main branch.

#### Expected

JWT can be decoded properly

#### Actual

JWT cannot be decoded, but function throws error.

### Additional Details

- Installed packages:

**Comment by guillaume-chervet** [comment]
Thank you @johakoch to have found that bug !

**Comment by guillaume-chervet** [comment]
hi @johakoch ,

Version 7.13.16-alpha.1278 should fix it !
Thank you so much !

**Comment by johakoch** [comment]
> hi @johakoch ,
> 
> Version 7.13.16-alpha.1278 should fix it ! Thank you so much, I think it was a recurrent issue. you found a bug i could not reproduce.

You're welcome. Now you have a test case :-)

**Comment by guillaume-chervet** [comment]
Yeah definitely

**Comment by Maingart** [comment]
@guillaume-chervet, hello!

Is it fix this bug?

https://github.com/AxaFrance/oidc-client/issues/1265

**Comment by guillaume-chervet** [comment]
hi @Maingart , it is hard for me to reproduce the referenced bug.
You can try 7.13.16-alpha.1278 version and tell me if it resolve it to help me.
