### ISSUE TITLE
"undefined" is not valid JSON while authenticating once deployed, working fine in local.

### ISSUE THREAD

**Issue by bhargavmullakuru** [AxaFrance/oidc-client#1274]
### Issue and Steps to Reproduce
Hi @guillaume-chervet , App was working fine in local, After deploying to server, it was throwing the below error.

"undefined" is not valid JSON at `getLoginParams`, Could you pls help me with this.
Her is my config format. 

```
{
authority:''
client_id:''
redirect_uri:''
response_type:''
scope:''
 storage: localStorage,
demonstrating_proof_of_possession : true
demonstrating_proof_of_possession_configuration : config
}
```

### Versions
7.14.1
### Screenshots
![Screenshot 2024-02-01 214606](https://github.com/AxaFrance/oidc-client/assets/26109320/e9c320d5-e54d-4bd3-88d3-b1d91db0447d)
![Screenshot 2024-02-01 214757](https://github.com/AxaFrance/oidc-client/assets/26109320/79f39326-19fd-4c07-8993-da63f23bbca0)

### Additional Details

- Installed packages:

**Comment by bhargavmullakuru** [comment]
@guillaume-chervet,  Seems like storage is not working when deployed in server. When debugged, the same storage object in local has diff values, whereas server Storage object doesn't have any values.

In local.
![image](https://github.com/AxaFrance/oidc-client/assets/26109320/c057875e-5e8d-4f2f-9803-f62a9cac8fd4)

in Dev, Storage was not created properly
![Screenshot 2024-02-01 224133](https://github.com/AxaFrance/oidc-client/assets/26109320/ea219fb9-50d4-4030-8856-e8e76dc1b1a2)

**Comment by guillaume-chervet** [comment]
hi @bhargavmullakuru , do you have a video which can help me to unsderstand user flow on your server?

At which stage does this happen?

**Comment by bhargavmullakuru** [comment]
@guillaume-chervet  Just normally deployed and tried to access Dev URL, it is throwing that error.
Let me do and send a screen recording

**Comment by guillaume-chervet** [comment]
hi @bhargavmullakuru ,

You may have a wrong configuration somewhere. I need more information to be able help you.

**Comment by bhargavmullakuru** [comment]
Yes @guillaume-chervet , but it's working fine in local. 🫣🥲

**Comment by Moraissz** [comment]
@bhargavmullakuru  We have the same problem, but even local it doesn't work

We figure out that its because the redirectUri param did not finish with '/authentication/callback'.

It's mandatory to end with '/authentication/callback' @guillaume-chervet ?

**Comment by guillaume-chervet** [comment]
Hi @Moraissz , the callback url can be whatever you want. OidcProvider need to be before any router in the component hierarchie to prevent router to catch the flow.

**Comment by guillaume-chervet** [comment]
@Moraissz what happen with your configuration set on this repository demo?

**Comment by Moraissz** [comment]
I didn't try my configuration set on the react demo , could try to se what happens.

That's strange, but somehow this undefined problem vanished when we put the /authentication/callback in the redirect url, without changing anything else.

We put the OidcProvider before everything in App.tsx

**Comment by bhargavmullakuru** [comment]
> hi @bhargavmullakuru ,
> 
> You may have a wrong configuration somewhere. I need more information to be able help you.

@guillaume-chervet  Here is my configuration.
```
{
    "authority": "https://idpstg.ice.ibmcloud.com/oauth2",
    "client_id": "6f4906fd-2e64-4296-a0e5-874773300c81",
    "redirect_uri": "https://appsdev.schools.nyc/msi/",
    "response_type": "code",
    "scope": "openid profile email offline_access",
    "post_logout_redirect_uri": "https://appsdev.schools.nyc/msi",
    "demonstrating_proof_of_possession": true,
    "demonstrating_proof_of_possession_configuration": {
        "importKeyAlgorithm": {
            "name": "RSASSA-PKCS1-v1_5",
            "hash": {
                "name": "SHA-256"
            }
        },
        "signAlgorithm": {
            "name": "RSASSA-PKCS1-v1_5",
            "hash": {
                "name": "SHA-256"
            }
        },
        "generateKeyAlgorithm": {
            "name": "RSASSA-PKCS1-v1_5",
            "modulusLength": 2048,
            "publicExponent": {
                "0": 1,
                "1": 0,
                "2": 1
            },
            "hash": {
                "name": "SHA-256"
            }
        },
        "digestAlgorithm": {
            "name": "SHA-256"
        },
        "jwtHeaderAlgorithm": "RS256"
    }
}
```
it was working fine in local. no idea why it's failing while accessing url.

**Comment by bhargavmullakuru** [comment]
@guillaume-chervet  is is possible to set and get that object key is `undefined `?

**Comment by guillaume-chervet** [comment]
hi @bhargavmullakuru ,

you redirect_uri is equal to post_logout_uri.

it shoulb be an unique url that OIDC client can use to catch the redirection :)

in the demo it looks like : 
redirect_uri: window.location.origin + '/authentication/callback',

**Comment by bhargavmullakuru** [comment]
@guillaume-chervet  I think library is not using `post_logout_uri` key. Let me try it by appending to `redirect_uri` '/authentication/callback'

**Comment by bhargavmullakuru** [comment]
after appending with '/authentication/callback' with `redirect_uri` it worked. Thanks for help @guillaume-chervet , if any issue, i will let you know.

**Comment by guillaume-chervet** [comment]
Hi @bhargavmullakuru feel free to close the issue when you think it is done.

**Comment by bhargavmullakuru** [comment]
@guillaume-chervet  ... Now after login, it was not redirecting properly to home.

It's displaying blank page with console errors.
![image](https://github.com/AxaFrance/oidc-client/assets/26109320/df340759-36ac-4b06-9d6c-8e20d4891b9f)

any suggestion ?
my jsx is below.
`<OidcProvider
      configuration={configuration}
      callbackSuccessComponent={CallbackSuccessComponent}
      onEvent={(configurationName, eventName, data) => {
        console.log("event...", configurationName, eventName, data);
      }}
    >
      <BrowserRouter basename={BASE_PATH}>
        <SettingsContext.Provider value={{ ...settings, configuration }}>
          <App />
        </SettingsContext.Provider>
      </BrowserRouter>
    </OidcProvider>`

Help needed. Thanks in advance.

**Comment by guillaume-chervet** [comment]
hi @bhargavmullakuru, is it okey for you, may we close this issue?

**Comment by bhargavmullakuru** [comment]
Yes, closing it.
