### ISSUE TITLE
Weird issues in making service worker implementation working (Struggling since long)

### ISSUE THREAD

**Issue by pgangwani** [AxaFrance/oidc-client#1283]
### Issue and Steps to Reproduce
I added oidcTrustedDomain setting to convert already working on service worker (web storage) approach for my enterprise application

### Versions
` "@axa-fr/react-oidc": "^7.15.4"`

### Screenshots
![Screenshot 2024-02-05 at 11 09 01 PM](https://github.com/AxaFrance/oidc-client/assets/14316332/c89740ef-7dc9-45eb-9ced-46d34b941e51)
![Screenshot 2024-02-05 at 11 02 18 PM](https://github.com/AxaFrance/oidc-client/assets/14316332/e3f28e41-3e7f-412b-a288-0a343e6acca8)

![Screenshot 2024-02-05 at 11 14 01 PM](https://github.com/AxaFrance/oidc-client/assets/14316332/3bb92f10-5019-4a2d-ac78-bae11ecf1432)
![Screenshot 2024-02-05 at 11 13 46 PM](https://github.com/AxaFrance/oidc-client/assets/14316332/56f0778b-9f54-4329-b126-8ea90179b496)

#### Expected
Service worker implementation should be working properly

#### Actual
Getting many weird issues, unable to even refresh the page.

### Additional Details
I think its even not able to initialize

- Installed packages:

**Comment by pgangwani** [comment]
hi @guillaume-chervet , Greetings!!
I know you must be busy. I am struggling since long to get service worker approach initialized. 

May I get your few minutes to review where and what I am doing wrong.

**Comment by guillaume-chervet** [comment]
Hi @pgangwani ,

Thank you for your issue :)

Do you have the content of your trustedDomains files? it seem to be an error from that file.

Here bellow the trustedDomain file from the demo :
https://github.com/AxaFrance/oidc-client/blob/main/examples/react-oidc-demo/public/OidcTrustedDomains.js

**Comment by pgangwani** [comment]
![Screenshot 2024-02-06 at 2 07 27 AM](https://github.com/AxaFrance/oidc-client/assets/14316332/1a7ea2de-01ab-49df-9cff-6149cd2c097c)

Sure @guillaume-chervet  please check the screenshot

**Comment by guillaume-chervet** [comment]
Hi @pgangwani , i will try tomorrow morning to setup a case like you did in the demo. It is possible that it is a bug.

**Comment by pgangwani** [comment]
Sure. Additionally, I would like to know that if in case service worker works with low confidence and we get any issue in app where we decide to turn off the service worker. Is there unRegisteration of service worker happens automatically ? or this is a feature request.

**Comment by pgangwani** [comment]
This issue is fixed by taking the latest oidc-sw & trusteddomain and replacing with above trustedomain. Not sure what suddently changed between 7.3.x to 7.15.

Also how to switch safely betweeen service woeker vs non service worker & vice versa by cleaning up/unregistering service worker

**Comment by pgangwani** [comment]
@guillaume-chervet As I said , somehow I was able to make default working but non default is not working. You might want to try in your sandbox once. For some reason I m not able to get repo working to test example like sandbox the way I am doing in real app. Hope you can provide insights !

**Comment by guillaume-chervet** [comment]
Hi @pgangwani , I'am not sure to understand your new problem? May you have more code example and details ?

if you use a specific configuration name, you have to set the configuration name in each components to rebranch to the correct configuration.

**Comment by pgangwani** [comment]
> Hi @pgangwani , I'am not sure to understand your new problem? May you have more code example and details ?
> 
> if you use a specific configuration name, you have to set the configuration name in each components to rebranch to the correct configuration.

**Comment by guillaume-chervet** [comment]
Hi @pgangwani do you have more information to share innorder to be able to help you?

**Comment by pgangwani** [comment]
We can close this. #1299 will cover some cleanup concerns and its discussion.
