### ISSUE TITLE
Cleanup missing : Toggling between service worker & non-service worker 

### ISSUE THREAD

**Issue by pgangwani** [AxaFrance/oidc-client#1299]
### Issue and Steps to Reproduce
Issues
1. Whenever we switch from non-service worker to service worker for a production app in same configurationName, we should cleanup storage like `storage.remove(oidc.${configurationName})`
2. On similar line if one switch from service worker to non-serviceworker , we should deregister the service worker with immediate effect and Let the storage be used for storing any token payloads etc

### Versions
any verison in 7.x.x

### Screenshots
![Screenshot 2024-02-15 at 11 20 38 PM](https://github.com/AxaFrance/oidc-client/assets/14316332/50e7e45b-d902-4a0d-b06f-9c75a54ffb69)
![Screenshot 2024-02-15 at 11 20 18 PM](https://github.com/AxaFrance/oidc-client/assets/14316332/1b1d3285-9309-4ff6-9976-82330c2709c4)

#### Expected

Cleanup / Deregistration should happen if we switch between most secured of service worker  and non service worker.

#### Actual
Either getting service worker not registering even after turning off the approch or getting storage having token payload forever. 
Sometime it gets stuck with Loading screen for users.

### Additional Details

We need to implement turn off & on for service worker approach

- Installed packages:

**Comment by pgangwani** [comment]
@guillaume-chervet PLease review this issue. Please let me know if any further details required .

**Comment by guillaume-chervet** [comment]
hi @pgangwani ,

I'am currious, why do you offer a way to the user to register/unregister service worker? What is your application need?

How to your actually unregistrer service worker ?

**Comment by pgangwani** [comment]
> hi @pgangwani ,
> 
> I'am currious, why do you offer a way to the user to register/unregister service worker? What is your application need?
> 
> How to your actually unregistrer service worker ?

What I meant is we shouldnt give user register/unregister capability but should be done by the library itself.
Couple of scenerios:
A)
1. Use non service worker approach and deploy
2. Notice the storage which holds all the tokens
3. Now, in the same server we enable service worker by build and deploy
4. Goto storage, tokens still exist.
5. This is clean up scnerio 1

B) 
1. Use service worker approach and deploy
2. Notice that service woerk is registered on / root of the site
3. Now, disable service worker approach by building the config, keep configurationName everything same and deploy
4. Service worker has not unregistered even though we are not using service worker approach
5. This is cleanup scnerios 2

**Comment by pgangwani** [comment]
@guillaume-chervet  did you get chance to look at above response?

**Comment by pgangwani** [comment]
Closing based on as designed
