### ISSUE TITLE
Need to modify ath value in dpop payload

### ISSUE THREAD

**Issue by bhargavmullakuru** [AxaFrance/oidc-client#1322]
### Issue and Steps to Reproduce

@guillaume-chervet  As per my server gateway, they need ath value divide by 2 in dpop jwt payload. 
if possible, can we have a extra param something  like makeAthHalfInJWT  divide by 2 (half)  in configuration itself like below.
From this code...
```
       const configuration = this.configuration;
        const claimsExtras = {ath: await base64urlOfHashOfASCIIEncodingAsync(accessToken),};
```
to...
```

        const configuration = this.configuration;
        const athValue= await base64urlOfHashOfASCIIEncodingAsync(accessToken);
        const claimsExtras = {ath: configuration?.makeAthHalfInJWT ?  athValue.slice(0, athValue.length / 2) : athValue ,};

```
If you want me to send custom ath value like below, i can send it as extra param to _generateDemonstrationOfProofOfPossessionAsync_ method.

`await oidc.generateDemonstrationOfProofOfPossessionAsync(
        accessToken,
        urlSplit[0],
        method,
        ath
      );`

Thanks in Advance.

### Versions
"@axa-fr/react-oidc": "^7.14.1"

### Screenshots
![image](https://github.com/AxaFrance/oidc-client/assets/26109320/1b66f6ba-9f97-45d8-8167-1d998a8c0192)
![image](https://github.com/AxaFrance/oidc-client/assets/26109320/990303e8-1f6c-4036-bea8-379b9cd4089b)

### Additional Details

- Installed packages:

**Comment by guillaume-chervet** [comment]
hi @bhargavmullakuru , thank you for the issue.
I'am not sure to understand why you need to devid it by 2 ? Do you have more details.

Are you using dpop inside service worker or whithout service worker?

**Comment by bhargavmullakuru** [comment]
@guillaume-chervet  . I'm not using service worker in my configuration. From another gateway end they are checking dpop ath divide by 2.

**Comment by guillaume-chervet** [comment]
Hi @bhargavmullakuru , we may can add an extras parameter so you will be able to override defaut properties by your own one.

**Comment by bhargavmullakuru** [comment]
@guillaume-chervet .. any update on this fix for new extras parameter ? 😁

**Comment by guillaume-chervet** [comment]
I will try to do it today @bhargavmullakuru :)

**Comment by guillaume-chervet** [comment]
I published 
v7.20.0-alpha.1393, but I'am not sure it will resolve your issue.

I pushed on main by mistake : https://github.com/AxaFrance/oidc-client/commit/c7793c9913128dbb82a60dff11261ca5b4749f0c
But it is an alpha.

**Comment by bhargavmullakuru** [comment]
@guillaume-chervet  Tried using that alpha, it was not accepting 4th parm.
![Image 01-01-1946 Saka at 11 44 AM](https://github.com/AxaFrance/oidc-client/assets/26109320/4ae63d02-812a-4d35-9d25-e35539c8180d)

**Comment by guillaume-chervet** [comment]
Sorry @bhargavmullakuru , I have created/pulished a new alpha => https://github.com/AxaFrance/oidc-client/pull/1325

**Comment by guillaume-chervet** [comment]
Any news @bhargavmullakuru ?

**Comment by bhargavmullakuru** [comment]
It was working with that alpha version and i'm able to pass custom keys. Let me know once it's merged to main release version. 
Thanks for your help @guillaume-chervet

**Comment by guillaume-chervet** [comment]
Thank you for your feedback @bhargavmullakuru ,
I released it :)
