### ISSUE TITLE
Issue with React-oidc: Endless "Redirecting" Message and Failure to Redirect to Homepage after Token Expiry

### ISSUE THREAD

**Issue by mohamed-isak** [AxaFrance/oidc-client#1330]
### Issue and Steps to Reproduce

I am encountering an issue with the React-oidc library where, upon token expiration, it shows a continuous "Redirecting" message instead of redirecting the user to the homepage after auto-login. This behavior persists even after the token has expired and auto-login is successful.

Access the application.
Wait for the token to expire.
Observe the continuous "Redirecting" message instead of being redirected to the homepage after successful auto-login.

Code: 

const userManagerConfig = {
    "authority": "http://localhost:8080",
    "automaticSilentRenew": false,
    "client_id": "",
    "client_secret": "",
    "redirect_uri": "[http://localhost:3001/callback"](http://localhost:3001/callback%22),
    "response_type": "id_token token",
    "scope": "openid email profile role",
    "silent_redirect_uri": "[http://localhost:3001/silent_callback"](http://localhost:3001/silent_callback%22),
    "loadUserInfo": true,
    "post_logout_redirect_uri": "http://localhost:3001"
}

<AuthenticationProvider
        configuration={userManagerConfig}
        loggerLevel={oidcLog.ERROR}
        isEnabled={true}
        authenticating={() => SpinnerComponent("Loading Login...")}
        callbackComponentOverride={() => SpinnerComponent("Redirecting...")}
        sessionLostComponent={() => SpinnerComponent("Session lost...")}
        customEvents={customEvents}
      >
        <OidcSecure>
          <Router>
            <AppRoutes />
            <Toaster />
          </Router>
        </OidcSecure>
      </AuthenticationProvider>      

### Versions
"dependencies": {
    "@axa-fr/react-oidc-context": "^3.1.7",
}
#### Expected
After the token expires, React-oidc should automatically redirect the user to the homepage upon successful auto-login.

### Additional Details

- Installed packages:

**Comment by guillaume-chervet** [comment]
Hi @mohamed-isak , it seems you are using a very old version and unmaintened of the library.
The best solution to help you is to migrate to the latest 7.X.X version.

**Comment by mohamed-isak** [comment]
Resolved
