### ISSUE TITLE
Something changed while fetching userinfo between 2 versions.

### ISSUE THREAD

**Issue by bhargavmullakuru** [AxaFrance/oidc-client#1336]
### Issue and Steps to Reproduce
Hi @guillaume-chervet , **There is something changed between 7.14.1 and 7.21.0.** 

Before in **7.14.1** my userinfo fetch was working fine, **authorization** header going with _Bearer xxxxx_ in header.
![Screenshot 2024-04-03 233927](https://github.com/AxaFrance/oidc-client/assets/26109320/0753d409-ce98-4d75-8a6b-d9256318f1aa)

In new version **7.21.0** i was getting **401** error while getting userinfo. there is something changed as it was going as _PoP xxxxx_ in **authorization** header.

![Screenshot 2024-04-03 233915](https://github.com/AxaFrance/oidc-client/assets/26109320/e7ba024b-528d-4a2d-9918-ed4c0edd03c9)

pls refer the Authorization header starting value in Attached screenshots. when i tried the failed request manually through postman with Authorization : Bearer xxxxxxx ... it was working fine. 

seems like something got changed in recent versions.

Could you please look into it. Thanks in Advance 

### Versions
 7.14.1 and 7.21.0
### Additional Details

- Installed packages:

**Comment by guillaume-chervet** [comment]
Hi @bhargavmullakuru thnak you for your feedback again :)

Hi need to set up a configurable way to inject dpop or not to a domains or not. I do not know how yet :/
https://github.com/AxaFrance/oidc-client/blob/ef1597ea2c6d41e8d61b6a27bc26f6ad40304a50/packages/oidc-client/src/fetch.ts#L24

**Comment by guillaume-chervet** [comment]
I have just published version 7.22.0-alpha.1416 that should do the job @bhargavmullakuru .

**Comment by bhargavmullakuru** [comment]
Let me check it. Thanks @guillaume-chervet

**Comment by bhargavmullakuru** [comment]
It's working now. Pls let me know once it is released. i will update the version. Thanks @guillaume-chervet

**Comment by bhargavmullakuru** [comment]
is it merged to main and released @guillaume-chervet  ?. so that we can close this issue. Thanks

**Comment by guillaume-chervet** [comment]
Hi @bhargavmullakuru , thank you for your feedback.
I will try to merge it before the end of the week.

**Comment by guillaume-chervet** [comment]
I published version 7.22.0 @bhargavmullakuru .
Thank you again.

**Comment by bhargavmullakuru** [comment]
Thanks @guillaume-chervet  . closing this
