### ISSUE TITLE
HOTFIX: Unable to compile the library using TypeScript 3.8.3

### ISSUE THREAD

**Issue by ivan-pelyno** [AxaFrance/oidc-client#1351]
### Issue and Steps to Reproduce
I am unable to compile/build the library using TypeScript 3.8.3. Here are the steps I have taken:

1. Installed TypeScript 3.8.3
2. Tried to build

### Versions
7.22.2
### Screenshots
![image](https://github.com/AxaFrance/oidc-client/assets/12561600/38afba11-7754-4cca-92be-ab4892997af6)

#### Expected
Make some minor changes in the following file
@axa-fr/react-oidc/dist/index.d.ts

- Instead of
`export { type OidcUserInfo, TokenRenewMode, OidcClient, TokenAutomaticRenewMode, OidcLocation } from '@axa-fr/oidc-client';`

- Modify the existing line to look like this
`export { TokenRenewMode, OidcClient, TokenAutomaticRenewMode, OidcLocation } from '@axa-fr/oidc-client';`
`export type { OidcUserInfo } from '@axa-fr/oidc-client';`

### Additional Details

- Installed packages:
    "typescript": "3.8.3",

**Comment by guillaume-chervet** [comment]
Thank you @ivan-pelyno 
version 7.22.3 fixed it :)

**Comment by ivan-pelyno** [comment]
@guillaume-chervet
Thank you so much for taking the time to fix the issue quickly !)

**Comment by guillaume-chervet** [comment]
May we close the issue @ivan-pelyno ?
