### ISSUE TITLE
Does the library support hash routes?

### ISSUE THREAD

**Issue by nandeeshwar-p** [AxaFrance/oidc-client#1367]
How to use the package when working with hash routes in React?

**Comment by guillaume-chervet** [comment]
hi @nandeeshwar-p ,

of course, this is describe in the documentation here : https://github.com/AxaFrance/oidc-client/tree/main/packages/react-oidc#readme.md

**Comment by guillaume-chervet** [comment]
I close this issue @nandeeshwar-p I think it is resolved
