### ISSUE TITLE
Error on Logout

### ISSUE THREAD

**Issue by iedokpayintsb** [AxaFrance/oidc-client#1374]
### Login.gov logout causes State error 
When logging out with Login.Gov I see an error message saying something like:  Error: State not valid (expected: null, received: xxxx)
I traced it back to [oidc-client](https://github.com/AxaFrance/oidc-client/tree/e8ad44f823fe89e28c6616ed3f63a1ff28554386)/[packages](https://github.com/AxaFrance/oidc-client/tree/e8ad44f823fe89e28c6616ed3f63a1ff28554386/packages)/[oidc-client]
Line 201. The code explicitly sets the state to null!

### Versions
"@axa-fr/oidc-client": "^7.22.5",
"@axa-fr/react-oidc": "^7.22.4"
### Screenshots
![LoginDOTGovLogoutError](https://github.com/AxaFrance/oidc-client/assets/127466175/c6cd41f1-ee80-4b33-b237-1f09aa99771d)
![LoginDotGovAuthErrorOnLogout](https://github.com/AxaFrance/oidc-client/assets/127466175/aacc1fad-7e86-49f0-aa6b-917bb5cc070e)
![image](https://github.com/AxaFrance/oidc-client/assets/127466175/c2f89781-518f-404c-bd2e-00229d5cf92b)

#### Expected
State should be valid until logout
#### Actual
State is not valid until logout
### Additional Details

- Installed packages:
"react": "^18.2.0",
"react-dom": "^18.2.0"

**Comment by guillaume-chervet** [comment]
hi @iedokpayintsb , thank you for your issue.

That strange, do you have a sample of your configuration ?

**Comment by iedokpayintsb** [comment]
import { nanoid } from 'nanoid';

export const Login_Gov_Config = {
    client_id: import.meta.env.VITE_LOGIN_GOV_CLIENT_ID,
    redirect_uri: `${window.location.origin}/authentication/callback`,
    silent_redirect_uri:`${window.location.origin}/authentication/silent-callback`,
    scope : ‘openid, email’,
    authority:’ https://idp.int.identitysandbox.gov’,
    service_worker_relative_url: "/OidcServiceWorker.js", // just comment that line to disable service worker mode
    service_worker_only: false,
    demonstrating_proof_of_possession: false,
    extras:{'acr_values':'http://idmanagement.gov/ns/assurance/ial/2', 'prompt':'select_account', 'nonce': nanoid(22), 'state':nanoid(50)}
};

**Comment by guillaume-chervet** [comment]
Thank you @iedokpayintsb . I will test with your parameters to try to reproduce it.

**Comment by guillaume-chervet** [comment]
hi @iedokpayintsb does version [7.22.9-alpha.1456](https://www.npmjs.com/package/@axa-fr/oidc-client/v/7.22.9-alpha.1456) fixe it?

**Comment by iedokpayintsb** [comment]
I will check!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
