### ISSUE TITLE
Hide the redirect to redirect_uri for the user

### ISSUE THREAD

**Issue by adrianchircats** [AxaFrance/oidc-client#1385]
### Issue and Steps to Reproduce

Hi,
Is it possible to hide from the end user the redirect to /authentication/callback?

### Versions
@axa-fr/react-oidc": "^7.22.6"

#### Actual
![image](https://github.com/AxaFrance/oidc-client/assets/55232039/02491285-3bcb-49ba-9898-ea96ec06b9a1)

### Additional Details

- Installed packages:

**Comment by guillaume-chervet** [comment]
hi @adrianchircats , 
Thank you for your Issue.
It is not possible this is a part of OIDC flow.
