### ISSUE TITLE
Token multiple call

### ISSUE THREAD

**Issue by YaoHure** [AxaFrance/oidc-client#1393]
### Issue and Steps to Reproduce

After logging into the application when I see in the log, there are a lot of calls to the token. Like about very 30sec or less ...

### Versions
    "@axa-fr/react-oidc": "^7.22.8",

### Screenshots
![image](https://github.com/AxaFrance/oidc-client/assets/49785625/fe223790-081f-487c-8b34-7e456a759069)

### Config 

`client_id: 'my_clientid',
    redirect_uri: window.location.origin + '/oidc-callback',
    silent_redirect_uri: window.location.origin + '/silent-oidc-callback',
    scope: 'profile offline_access openid profile_extended + my_scopes',
    authority: GetConfig('ssoUrl'),
    service_worker_relative_url: '/OidcServiceWorker.js',
    service_worker_only: true,
    demonstrating_proof_of_possession: false,
    acr_values: 'externalAmrAzureEnable:1',
    loadUserInfo: true,
    extras: {
        acr_values: 'externalAmrAzureEnable:1',
    },`

- Installed packages:
Using react.js and vite

**Comment by guillaume-chervet** [comment]
hi @YaoHure ,

Did you tried to set token_renew_mode: TokenRenewMode.access_token_invalid,
in your configuration?

Do you have a sample of your tokens ?

**Comment by YaoHure** [comment]
Hi @guillaume-chervet, 

When i try to put the  token_renew_mode: TokenRenewMode.access_token_invalid it worse the token is call almost every 5 secs.

Here is an sample of tokens and scope that i send :

```
{
    "id_token": "abcdJhbGciOiJSUzI1NiIsImtpZCI6IkNEMTIzNEE2NzZBMTlGN0U5MzQ5MkQ0QzQ2Q0IyNkZEIiwidHlwIjoiSldUIn0.eyJuYmYiOjE3MjAxMDE2NTYsImV4cCI6MTcyMDgcyMDEwMTU1OSwiaWRwIjoiQXp1cmVBRCIsImFtcjI6WyJleHRlcmAvQ3EXJtDlTGmXrAPrC3kRlyFZ8fYuBtAwFc2qFY4s_gyAHTDkBPI1bsDT5n9VtTch8HI8f6aWMRSCuWQ5C3aUzY3vbLKoa34XQ0HQLQxrdI1l5BYdxgMNb5zxz5-ovxZb5WInP9hqKDSr8_LIjPRYflmJ8U1ddqGxnAlDWRXzA7vQQtVHJZGoZVpFGFBB5Sxi6d6WhR7lhOsniKtRC84nTxZs0gRyO-HyYVqUqtfLcyo2uOzxQ",
    "access_token": "abcdJhbGciOiJSUzI1NiIsImtpZCI6IkNEMTIzNEE2NzZBMTlGN0U5MzQ5MkQ0QzQ2Q0IyNkZEIiwidHlwIjoiSldUIn0.eyJuYmYiOjE3MjAxMDE2NTYsImV4cCI6MTcyMDg2NDU1NiwiaXNzIjoiaHR0cHM6Ly90LWZlLW15Yi1zc28tbWFzdGVyLmVkaXR1c2hvbWUubHUiLCJhdWQiOiJ0aWNrZXRpbmdfdWkiLCJpYXQiOjE3MjAxMDE2NTYsImF0X2hhc2giOiJDSUNPMkVZNkI4Z3FoUkhaUUNLUFhBIiwic3ViIjoiMTIzNGFjZGVmLTA5OGMtNDUyMC05ZWQxLWJhZjUzMjI4OTZlOCIsImF1dGhfdGltZSI6MTcyMDEwMTU1OSwiaWRwIjoiQXp1cmVBRCIsImFtcjI6WyJleHRlcm5hbCJdfQ.JrLSqL8AvQ3EXJtDlTGmXrAPrC3kRlyFZ8fYuBtAwFc2qFY4s_gyAHTDkBPI1bsDT5n9VtTch8HbE70pl8A0bFvBepRFR_Bf4N5lzm-XvLZgVFk1FJduOBgBd6gThFYDQdXOsG3W2MOTY2v1Yb4In9gWFBtO0kALdBPQy5I8f6aWMRSCuWQ5C3aUzY3vbLKoa34XQ0HQLQxrdI1l5BYdxgMNb5zxz5-ovxZb5WInP9hqKDSr8_LIjPRYflmJ8U1ddqGxnAlDWRXzA7vQQtVHJZGoZVpFGFBB5Sxi6d6WhR7lhOsniKtRC84nTxZs0gRyO-HyYVqUqtfLcyo2uOzxQabcdJhbGciOiJSUzI1NiIsImtpZCI6IkNEMTIzNEE2NzZBMTlGN0U5MzQ5MkQ0QzQ2Q0IyNkZEIiwidHlwIjoiSldUIn0.eyJuYmYiOjE3MjAxMDE2NTYsImV4cCI6MTcyMXvLZgVFk1FJduOBgBd6gThFYDQdXOsG3W2MOTY2v1Yb4In9gWFBtO0kALdBPQy5I8f6aWMRSCuWQ5C3aUzY3vbLKoa34XQ0HQLQxrdI1l5BYdxgMNb5zxz5-ovxZb5WInP9hqKDSr8_LIjPRYflmJ8U1ddqGxnAlDWRXzA7vQQtVHJZGoZVpFGFBB5Sxi6d6WhR7lhOsniKtRC84nTxZs0gRyO-HyYVqUqtfLcyo2uOzxQ9wZSI6WyJvcGVuaWQiLCJwcm9maWxlIiwicHJvZmlsZV9leHRlbmRlZCIsInBob2VuaXguc2VhcmNoLnJlYWQiLCJkb21haW4uY29tcGFuaWVzLnJlYWQiLCJkb21haW4udGlja2V0aW5nLnJlYWQiLCJkb21haW4udGlja2V0aW5nLndyaXRlIiwiYXBpX2F1dGhvcml6YXRpb25fYWNjZXNzIiwiZG9tYWlUu7avnR9TH7C-lhbu_UBv86_bOxWZzm3s7r0lRIshAl4F-qU2whcfegmNxvEqiv91XLDaCsDMr9XAYuaUgHY1Y4vw593J0xfPfO4RhFgo9smSPySCe3YDpBphhe6Q4AwQkzqp8PiBpbmIwxXQE4OgaUBKAKQelahX0dq3AF_hiJ4uBBoRDi_8picnMqEVRFoNLZMNMXuMQK0a8FS-MA_5oLkktWudpokd7sODsL5_IyHWILFteFLQpc4cR61qSlHI08aW95tQDtx7DLnNQ",
    "expires_in": 120,
    "token_type": "Bearer",
    "refresh_token": "885552A4C3A2D9AA20E008F7001C259844Y6ED00EFA1FBB5845EDFRE80",
    "scope": "openid profile profile_extended offline_access"
}
```

**Comment by guillaume-chervet** [comment]
Do you know the lifetime of your access_token and refresh_token ? @YaoHure

**Comment by guillaume-chervet** [comment]
You can also set the default behavior to refresh only when needed https://github.com/AxaFrance/oidc-client/blob/main/examples%2Freact-oidc-demo%2Fsrc%2Fconfigurations.ts#L20

It require you to use fetch from the library to ensure a correct behavior.

**Comment by YaoHure** [comment]
access_token : 120 and refresh_token : 30 days

**Comment by guillaume-chervet** [comment]
hi @YaoHure ,
it will ask for a new token only when needed. It require to use for example https://github.com/AxaFrance/oidc-client/blob/388bd33a54c546afeee496b0f7d58f2c4f51da5e/examples/react-oidc-demo/src/FetchUser.tsx#L50

or to use this method before an http call :

https://github.com/AxaFrance/oidc-client/blob/388bd33a54c546afeee496b0f7d58f2c4f51da5e/packages/oidc-client/src/fetch.ts#L18

**Comment by YaoHure** [comment]
Hi @guillaume-chervet 
Can you please provide me a real example of implementation of : 

` const { fetch } = useOidcFetch(window.fetch, props.configurationName); `

cause i don't understand what should i put instead of  props.configurationName .

**Comment by guillaume-chervet** [comment]
configurationName is not mandatory @YaoHure , default is "default". it is used when you have multiple authentication with multiple configuration.

**Comment by YaoHure** [comment]
I will close this issue i found the solution
