### ISSUE TITLE
Snyk issue: code analysis (CWE-547)

### ISSUE THREAD

**Issue by pgangwani** [AxaFrance/oidc-client#1408]
### Issue and Steps to Reproduce
Hello @guillaume-chervet and maintainers, 
I am seeing below error of snyk in analysis:
> Avoid hardcoding values that are meant to be secret. Found a hardcoded string used in here.
[CWE-547](https://cwe.mitre.org/data/definitions/547.html)

### Versions
all versions (7.18.1 and above)

### Screenshots
![Screenshot 2024-07-11 at 7 05 04 PM](https://github.com/AxaFrance/oidc-client/assets/14316332/723185e6-873f-42b1-8687-1875472bcca2)

#### Expected
No snyk issue should come from library generated files

#### Actual
[CWE-547](https://cwe.mitre.org/data/definitions/547.html) is found in public files specifically OidcServiceWorker.js

### Additional Details

- Installed packages:

**Comment by guillaume-chervet** [comment]
hi @pgangwani  thank you again for your issue :)

It is a false positive. These values are not secrets

**Comment by pgangwani** [comment]
Yeah I understand it is treating as hardcoding of accesstoken. There is recommendation in tool: 
![Screenshot 2024-07-12 at 11 19 31 AM](https://github.com/user-attachments/assets/e3711b05-d45d-4389-bf7c-0fffd9eb305e)

Not sure if we can do this. This might break. Thoughts?

**Comment by jafin** [comment]
@pgangwani that recommendation appears to be for a secret, as @guillaume-chervet as hinted, this is not a secret, its a const value.  I think the best thing you may try is in SYNK set the issue to ignore as false positive.

**Comment by pgangwani** [comment]
if any of you can answer #1420 , I can close both.

**Comment by pgangwani** [comment]
Closing as last comment in #1420
