### ISSUE TITLE
Question: OIDCServiceWorker.js

### ISSUE THREAD

**Issue by pgangwani** [AxaFrance/oidc-client#1420]
### Issue and Steps to Reproduce

hello Maintainers, I have a query if we can put `OIDCServiceWorker.js`  in gitignore as anyway it is generated in  every yarn installl script. Is it good practice ?
### Versions
All

### Additional Details
Related issue : https://github.com/AxaFrance/oidc-client/issues/1408
If I dont commit, I dont see any snyk issue 🥇 

- Installed packages:

**Comment by pgangwani** [comment]
@guillaume-chervet Please leme know your thoughts

**Comment by guillaume-chervet** [comment]
It is a good pratice to do it @pgangwani .
OidcServiceWorker.js should be in .gitignore.

**Comment by pgangwani** [comment]
Thanks closing it.
