### ISSUE TITLE
Logout doesn't end all tabs sessions

### ISSUE THREAD

**Issue by Moraissz** [AxaFrance/oidc-client#1428]
### Issue and Steps to Reproduce

When we open several tabs and logout in one of them, some tabs don't lose the session. In those tabs we can keep using the app without any problem until it tries to do some auth related operation ( Ex: refresh the token)

It’s possible to reproduce in the demo https://black-rock-0dc6b0d03.1.azurestaticapps.net/ 

To reproduce in demo:

1 - Login
2 - Open several tabs ( i did with 7 tabs)
3-  Logout in one of the tabs
4- Not every tab is going to be without session

### Screenshots
![image](https://github.com/user-attachments/assets/758f5a64-79c3-4801-a0ff-34e269b5241b)
![image](https://github.com/user-attachments/assets/d9d94007-8449-4edc-8614-13c69f7191c0)

**Comment by guillaume-chervet** [comment]
Thank you @Moraissz for that issue!
As soon as i have a computer i will try to reproduce it. Do you use a specific browser?

I'm sure it will be fun to fix it :)
