### ISSUE TITLE
Configuration option `service_worker_register` do not work as documented

### ISSUE THREAD

**Issue by thiscode** [AxaFrance/oidc-client#1439]
### Issue and Steps to Reproduce

According to the instructions, you should use the option `service_worker_register` to inject your own logic loading the service worker. However, this is only possible if you also set the option `register` to `true`. This may be a leftover from old versions.

### Versions

`@axa-fr/oidc-client@7.22.22`

#### Expected

Setting the `service_worker_register` option should be enough.

#### Actual

You have to set the option `register` to a truly value.

### Additional Details

The affected section contains a query that is probably outdated:

```js
  if (configuration.register) {
    registration = await configuration.service_worker_register(serviceWorkerRelativeUrl);
  } else {
    registration = await navigator.serviceWorker.register(serviceWorkerRelativeUrl);
  }
```

I tried to maintain backwards compatibility with my fix:

```js
  if (configuration.register || configuration.service_worker_register) {
    registration = await configuration.service_worker_register(serviceWorkerRelativeUrl);
  } else {
    registration = await navigator.serviceWorker.register(serviceWorkerRelativeUrl);
  }
```

**Comment by guillaume-chervet** [comment]
this issue sould be ok now @thiscode thank you very much for your help !
