### ISSUE TITLE
Token request failed

### ISSUE THREAD

**Issue by egoreq294** [AxaFrance/oidc-client#1442]
### Issue and Steps to Reproduce

Hi @guillaume-chervet

When I open the page, I have error component and the token requset failed error in console, although I haven't even tried to go to keylock yet. This happends with `window.location.origin` redirect uri, but when i change it to `window.location.origin + '/anything'` in configuration and server settings, everethying is ok. Can I set this up so than `window.location.origin` uri works too?

My configuration and usage
```tsx
const configuration = {
  client_id: "my-client",
  redirect_uri: window.location.origin,
  scope: "openid profile", // offline_access scope allow your client to retrieve the refresh_token
  authority: "http://localhost:8080/realms/my-realm",
  service_worker_relative_url: "/OidcServiceWorker.js",
  service_worker_only: true,
  demonstrating_proof_of_possession: false,
};

const Loading = () => <p>Loading</p>;
const AuthenticatingError = () => <p>Authenticating error</p>;
const Authenticating = () => <p>Authenticating</p>;
const SessionLost = () => <p>Session Lost</p>;
const ServiceWorkerNotSupported = () => <p>Not supported</p>;
const CallBackSuccess = () => <p>Success</p>;

const App = () => {
  return (
    <OidcProvider
      configuration={configuration}
      loadingComponent={Loading}
      authenticatingErrorComponent={AuthenticatingError}
      authenticatingComponent={Authenticating}
      sessionLostComponent={SessionLost}
      serviceWorkerNotSupportedComponent={ServiceWorkerNotSupported}
      callbackSuccessComponent={CallBackSuccess}
    >
      <UrqlProvider>
        <Home />
        <UrqlFetch />
      </UrqlProvider>
    </OidcProvider>
  );
};

```
UrqlFetch component doesnt matter, Home component has login and logout button, like in demo

### Versions
7.22.22

### Screenshots

![image](https://github.com/user-attachments/assets/15847b9a-a883-4604-8150-963747c19fa2)

**Comment by guillaume-chervet** [comment]
Hi @egoreq294 , it can work if you use a hash route in your callback like :
#auth_callback

**Comment by egoreq294** [comment]
Thanks, it works for me, but I have invalid redirect uri from keycloak on next step. Is is possible to do http://localhost:3000 as valid redirect uri on server and my app?

**Comment by guillaume-chervet** [comment]
I am not sure to understand @egoreq294 , do you have more information ? Keycloack should be compatible with hash router.

**Comment by egoreq294** [comment]
I have keycloak server with valid redirect uri `http://localhost:3000` and i cant change this. How do i set up the app so that everything works correctrly, if I configure `redirect_uri: window.location.origin` i have an error in console token request failed. If I configure `redirect_uri: window.location.origin + '#auth_callback'` i have an error from keycloak `invalid parameter: redirect_uri`

**Comment by guillaume-chervet** [comment]
I'am not sure that keycloak. DId you find a solution @egoreq294 ?

**Comment by egoreq294** [comment]
We can change redirect uri in keycloak server to `http://localhost:3000/authentication/callback` and now it works)
