### ISSUE TITLE
oidcClient.fetchWithTokens is using expired access token

### ISSUE THREAD

**Issue by Mikilll94** [AxaFrance/oidc-client#1447]
### Issue and Steps to Reproduce

After updating to latest version 7.22.24, there is a bug when access token is expired.

When access token is expired `/token` call is made but subsequent calls in my app are still using the expired access token.

I am not using service worker. Instead I am using `oidcClient.fetchWithTokens` for all my calls in the app.

### Versions
7.22.24

#### Expected
`oidcClient.fetchWithTokens` should always use a valid access token.

#### Actual
`oidcClient.fetchWithTokens` is using expired access token.

### Additional Details

This was working in my app in version 7.19.6

**Comment by guillaume-chervet** [comment]
O thank you @Mikilll94 , for this feedback ! I have reproduce it to fix it quickly!
