### ISSUE TITLE
Use of window.location.replace to initiate login call

### ISSUE THREAD

**Issue by synapxe-siang13** [AxaFrance/oidc-client#1450]
### Issue and Steps to Reproduce

After SSO and redirecting to the webpage, the history stack is duplicated in Safari or IOS due to `window.location.href`. Is there any way to change this behaviour?

**Comment by guillaume-chervet** [comment]
HI @synapxe-siang13, Thank you for your issue,

You can inject your own behavior inside the OidcProvider :

https://github.com/AxaFrance/oidc-client/blob/4f9ca8e903fc286f4d72ce069ad92873624ca2d3/packages/react-oidc/src/OidcProvider.tsx#L44C14-L44C28

**Comment by synapxe-siang13** [comment]
@guillaume-chervet Thank you for your reply. I will test this out.
