### ISSUE TITLE
State not valid (expected: ..., received: ...)

### ISSUE THREAD

**Issue by bernhard-braeu** [AxaFrance/oidc-client#1451]
### Issue and Steps to Reproduce
I'm trying to re-authenticate the user in the SessionLost Component when the users logs out in the same application on a different tab.

`export const SessionLost = () => {
    ...
        oidc.loginAsync(location.href, { 'login_hint': userEmail });
    ...

   
};
`
After the call, the authorize endpoint of our identity server is called with a new state value, the same state is returned to the callback url of my application.

But then i get the error, that an old state is expected, not the new one:

suppress-nextjs-warning.ts:7  Error: State not valid (expected: jHR5nIRPKTpJEijI, received: 4KePHGMLAGCwNBxn)
    at index.js:1310:13

Am i using the loginAsync method wrong?
We are using the service worker mode.

### Versions
7.22.24

### Screenshots
![image](https://github.com/user-attachments/assets/89221065-15be-47aa-94d6-52df0ed2018a)

![image](https://github.com/user-attachments/assets/c6901ee2-16c7-4bf1-8120-667e88b811ea)

### Additional Details

- Installed packages:

**Comment by guillaume-chervet** [comment]
hi @bernhard-braeu , thank you for your issue.

Do you have more code about how your use the library? Does the demo works with your own OIDC configuration?

**Comment by bernhard-braeu** [comment]
Everything else from your library just works perfectly fine!
Its just this special issue to automatically start the login flow when the session is lost (in our case when the user logs out in the same application in another tab).

We are using the OidcProvider and implemented all components on our own:
`
 <OidcProvider
            authenticatingComponent={Authenticating}
            authenticatingErrorComponent={AuthenticatingError}
            callbackSuccessComponent={CallbackSuccess}
            configuration={configuration}
            loadingComponent={Loading}
            sessionLostComponent={SessionLost}
        >
           {children}
        </OidcProvider>
`

In the session lost component i'm trying to start the login flow automatically with some extra parameters for our Identity Server to know which user it should try to automatically log in:

`
export const SessionLost = () => {
    const { t } = useTranslation();
    const userEmail = useAtomValue(userEmailAtom);
    const getOidc = OidcClient.get;
    const oidc = getOidc('default');

    if (userEmail) {
        // prettier-ignore
        oidc.loginAsync('/', { 'login_hint': userEmail });
    }

    return (
        <ErrorLayout
            description={t('reauthenticate', 'Your session has expired. Please re-authenticate')}
            title={t('sessionTimedOut', 'Session timed out')}
        />
    );
};

`

**Comment by guillaume-chervet** [comment]
Oh thank you @bernhard-braeu i understood ypur flow. I will make sime test today to try to reproduce it!

**Comment by bernhard-braeu** [comment]
Yes

**Comment by ToaiLe1609** [comment]
hi @guillaume-chervet, Do you have any ideas for this? I had the same problem and couldn't find a solution, thanks!

**Comment by guillaume-chervet** [comment]
Hi @bernhard-braeu , i am not sure but may be last release fix a little this error. I am on it but i do not know how to reproduce properly.

**Comment by ToaiLe1609** [comment]
hi @guillaume-chervet, i also had the same problem. i reproduced it by clearing session storage my page on logout then login and the problem happened. I think the problem occurs when the application initializes but the session storage does not create the necessary fields

**Comment by bernhard-braeu** [comment]
> Hi @bernhard-braeu , i am not sure but may be last release fix a little this error. I am on it but i do not know how to reproduce properly.

Unfortunately it still doesn't work with the newest version, but now i get a different error:

![image](https://github.com/user-attachments/assets/359b7abf-3ba0-45b4-b45e-e88657da1c28)

**Comment by guillaume-chervet** [comment]
hi @bernhard-braeu @ToaiLe1609 , do you have a way to reproduce it with the demo? https://black-rock-0dc6b0d03.1.azurestaticapps.net/
I have play the 2 last days with and conot reproduce it.

**Comment by ozanmanav** [comment]
> hi @bernhard-braeu @ToaiLe1609 , do you have a way to reproduce it with the demo? https://black-rock-0dc6b0d03.1.azurestaticapps.net/ I have play the 2 last days with and conot reproduce it.

I have same error with different flow, can you please check this video? @guillaume-chervet 

https://www.loom.com/share/de5e6ec2c0e3498f981b711ccd3adacc?sid=ebe7c1f4-3cce-4c7e-9c6d-4a2b40f3f96a

Flow is: Open two different tab for application and try login for firsat one. Second one (last opening one) is working but first one is not working. You can see in the loom video. Thanks

**Comment by guillaume-chervet** [comment]
Thank you @ozanmanav, for this case I can do something !

**Comment by guillaume-chervet** [comment]
@bernhard-braeu , do you still have problem with the latest version?

**Comment by bernhard-braeu** [comment]
> @bernhard-braeu , do you still have problem with the latest version?

It works with the latest version, thank you!!

**Comment by ozanmanav** [comment]
> Thank you very much @ozanmanav, for this case I can do something !

Hey @guillaume-chervet , how can we fix this issue? I can fork and apply in there also, when we initiated application with twice login only last login link is working.

**Comment by ozanmanav** [comment]
Case:

Open application link it is redirecting to login page,
Open second tab app link and it is redirecting again login page,

so we have two different login page now. But if we try login for first login page, it is getting this error:

<img width="860" alt="image" src="https://github.com/user-attachments/assets/8fa3be8a-fbd7-447e-94ee-b88d8e4d7b96">

Latest opened login page is working fine.
