### ISSUE TITLE
Authentication error when user stays o login page for an extended period

### ISSUE THREAD

**Issue by radk0s** [AxaFrance/oidc-client#1455]
### Issue and Steps to Reproduce

Initial login to the app may not work when IDP login screen is opened for a longer time.

1. Initiate login in the demo app https://black-rock-0dc6b0d03.1.azurestaticapps.net/ (single tab is required to reproduce).
2. Wait on login page ~5 mins (may be shorter, depends on browser) until service worker is stopped. Alternatively, worker may be paused immediately on `chrome://serviceworker-internals/`.
3. Provide credentials and login to the app.
4. Application throws authentication error on login redirect and is stuck on error page.   
    <img width="574" alt="Screenshot 2024-09-25 at 09 36 59" src="https://github.com/user-attachments/assets/bfba69e5-e128-4905-a208-355e55ff2784">
    <img width="969" alt="Screenshot 2024-09-25 at 09 38 39" src="https://github.com/user-attachments/assets/a39dc971-e74d-483c-af44-cd53fd73624a">

#### Expected

Login redirect should successfully authenticate the user, who will stay on the login screen a bit longer.

#### Actual

Application throws authentication error as cannot get access token when user stays on login screen a bit longer.

### Additional Details

This is scenario where OidcKeepAliveServiceWorker mechanism is not working as we don't have instance of the app when IDP login screen is opened. When login redirect is performed worker is not up on time and app is trying to fetch tokens without injected `code_verifier`.

**Comment by guillaume-chervet** [comment]
Hi @radk0s thank you for your issue. I was searching the problem, it help me to understand what is happening.
