### ISSUE TITLE
undefined is not an object (evaluating 'navigator.locks.request')

### ISSUE THREAD

**Issue by mteterel** [AxaFrance/oidc-client#1462]
### Issue and Steps to Reproduce

I'm seeing several reports on our Sentry that Safari users (exclusively, mobile and desktop) have the lib throw an unhandled error. The message is as follow :
`undefined is not an object (evaluating 'navigator.locks.request')`

It is located in the renewTokensAndStartTimerAsync method. The logic looks able to handle a missing lock, and should be adaptable to handle hte case where the navigator.locks API is not available.

### Versions

7.22.16 at the moment

**Comment by guillaume-chervet** [comment]
Thank you very much @mteterel for this feedback.
I will try too fix it quickly !
