### ISSUE TITLE
OIDC session stuck in limbo

### ISSUE THREAD

**Issue by mteterel** [AxaFrance/oidc-client#1463]
### Issue and Steps to Reproduce

It happens to several of our users that a failure at loading the session from the remote OIDC server makes the lib misbehave. The oidcUserLoadingState indicates "User loaded" but the oidcUser is null. It results in our app loading "fine" but with no profile information to display and no access token to use. None of the fallback components (Session Lost etc..) are run.

It seems that it uses its own cached version of a previous successful call to the userinfo endpoint and ignores the more recent failure to obtain it from the remote.

The only solution I found so far is to force a token renewal which results in an error and then the lib proceeds as expected (redirects to the login page).
```typescript
// Sometimes the OIDC lib does not consider the state expired or invalid.
  // It says the User exists but it's actually null and the lib gets stuck.
  // Forcing a refresh token allows the lib to process normally.
  useEffect(() => {
    if (oidcUserLoadingState === 'User loaded' && !oidcUser) {
      alert('Votre session a expiré, veuillez vous reconnecter.');
      auth.renewTokens();
    }
  }, [auth, oidcUser]);
```

EDIT : This fix looks inefficient, and can cause the application to repeatedly execute the alert(), not sure why yet.

For reproduction, you can log into your application using a first OIDC remote. Then change the remote authority URL and reload the app. It results in the same behavior. My guess is that there should also be revalidation of the active authority URL with the previously cached data.

### Versions

7.22.16 at the moment

**Comment by guillaume-chervet** [comment]
Hi @mteterel , version 7.22.26 should fix your problem.

**Comment by mteterel** [comment]
Hi,

Negative, I'm having the same issue with the latest version using the steps I listed. On initial page load I see a call to the openid-configuration then 2 more to the userinfo endpoint that returns a 401. The 401 is not handled properly and the user state becomes "User loaded" anyway.

**Comment by guillaume-chervet** [comment]
Does version 7.22.27 works? Do you have a sample of your configuration ?

**Comment by guillaume-chervet** [comment]
I can reproduce it sometime @mteterel  but I still did not understand how clearly reproduce it !
I Think it happen when i leave the computer and come back few hours latter.

**Comment by mteterel** [comment]
I was able to reproduce it like you said, it turns out there are 2 different issues, more or less related : 

(This was however with v7.22.25, it may have been fixed in the newer versions)

**Issue 1 : After some time has passed (what just happened to me)**

- Come back after some time away
- The lib will call the token endpoint with the refresh_token
- Server responds with a valid new access_token and refresh_token
- The lib gets stuck in processing or something, for around 3-4 seconds
- It will then call the userinfo endpoint with the previous access_token that had expired
- Userinfo fails and the lib state turns into "User loaded" state but with oidcUser being null

**Issue 2 : Change of the authority server URL**

- In this case, I assume it considers the access_token and/or refresh_token still valid
- It will call the userinfo endpoint with the access_token from the previous authority URL
- Server answers 401 Unauthorized
- Lib state turns into "User loaded" state but with oidcUser being null

I'll try with the 7.22.27 and see how it goes.

**Comment by mteterel** [comment]
Same problem (Issue 1) with the latest version :

![image](https://github.com/user-attachments/assets/3a40f513-3db6-4d28-aea8-19acfaeae7f1)

**Comment by mteterel** [comment]
The fix I listed this morning does not work, it will call the token and userinfo endpoints after the 10s lock, but the new user information doesn't get dispatched in the lib state, so oidcUser stays null.

I will try again with the newer version.

**Comment by guillaume-chervet** [comment]
Version 7.22.28 seems to work on my side. @mteterel

**Comment by mteterel** [comment]
Seems to work on my end as well !

![image](https://github.com/user-attachments/assets/75bbc4b9-ab1e-4b25-a8bd-67c9e19fd00e)

Thank you for your reactivity and for the time you've taken during the week-end ! 👍

**Comment by guillaume-chervet** [comment]
Thank you for your help @mteterel too 😀
