### ISSUE TITLE
Share token between two differents websites 

### ISSUE THREAD

**Issue by YaoHure** [AxaFrance/oidc-client#1467]
### Issue and Steps to Reproduce

Hi ! 

I would like to how if it's possible to share a token between two differents websites with the same domaine. Like site1.company.com site2.company.com. 

If it's possible can you please tell me the step to follow to make that 

### Versions

 "oidc-client-ts": "^3.0.1",
  "@axa-fr/react-oidc": "^7.22.8",

**Comment by guillaume-chervet** [comment]
hi @YaoHure , I do not think you can do it.
But if your OIDC server is Something oidc.company.com, you can enable silentsignin and your users can be automatically logged in once Identification/Authentication is passed once. oidc.company.com cookies will be used behind the sceene.

**Comment by YaoHure** [comment]
Hi @guillaume-chervet ! Oh ok i see. When you said silentsignin do you mean this : 
` silent_login_uri ` ?
So i should add this to the configuration + the url to trigger the login

**Comment by YaoHure** [comment]
@guillaume-chervet any news ? :)

**Comment by guillaume-chervet** [comment]
Yes it is that property but for your use cases you have to trigger it by code. Sample is available in the demo inside multitab page.

**Comment by YaoHure** [comment]
Okay, it works with the silent_login_uri; you just need to wrap everything with the oidc_secure. Thank for your help ! 

I'm putting my code here in case someone else has the same question. With this method, there's no need for a login button; the user automatically logs in to the SSO and is redirected to the homepage or elsewhere.

```
const configuration = {
// your scope or other config that you need for your website 
    redirect_uri: window.location.origin + '/oidc-callback',
    silent_redirect_uri: window.location.origin + '/silent-oidc-callback',
 }
```

Implementation: 

```
        <OidcProvider configuration={configuration}>
            <OidcSecure>
               <Router>
                    // your routes
               </Router>
            </OidcSecure>
        </OidcProvider>

```
