### ISSUE TITLE
Debug logging included in release build

### ISSUE THREAD

**Issue by KristianMH** [AxaFrance/oidc-client#1468]
### Issue and Steps to Reproduce
Hi @guillaume-chervet 

It seems you may have forgotten to remove some debug logging in your recent development.

We updated the package from 7.22.24 to 7.22.28 yesterday and noticed this additional logging in our development consoles.

I can see it is introduced in this PR:
[here](https://github.com/AxaFrance/oidc-client/pull/1465/files#diff-f90f494095f3484d3eb0a74f1fc5d4397691a0c28a3c3438d92c65dc54eda31aR31-R32)
 and [here](https://github.com/AxaFrance/oidc-client/pull/1465/files#diff-bedcd3326536db8e0caec18334ab74abfc8735c836ace6836512ce04425f7343R220-R221)

### Versions
7.22.88

### Screenshots

![image](https://github.com/user-attachments/assets/eb657ddd-e04d-4400-9886-9bb7cf20dcdc)

**Comment by guillaume-chervet** [comment]
Thank you @KristianMH for your issue. Very sorry for that. I fix it as quickly as possible.

**Comment by pavankjadda** [comment]
I second this

**Comment by pavankjadda** [comment]
@guillaume-chervet I still see this version 7.22.30 and 7.22.31

**Comment by KristianMH** [comment]
@guillaume-chervet  Thanks for the quick turnaround.

I can see in 7.22.32, All the logging have been removed.
