### ISSUE TITLE
After 7.22.32 upgrade, the application enters an infinite loop and constantly performs sw unregister and register.

### ISSUE THREAD

**Issue by ozanmanav** [AxaFrance/oidc-client#1475]
### Issue and Steps to Reproduce

After the latest version, the application enters an infinite loop and constantly performs sw unregister and register.

I guess this bug related with this commit: https://github.com/AxaFrance/oidc-client/commit/cc731c15f1d72ce4d21a7958ca15128ae1dcdd89

@guillaume-chervet  please help for this, thanks.

### Versions

7.22.32

**Comment by guillaume-chervet** [comment]
Hi @ozanmanav , did you update the service worker file to synchronize you app version?
This version is in production on my side whithout any problem.

**Comment by ozanmanav** [comment]
It seems resolved with latest version, thanks!
