### ISSUE TITLE
React Demo running on localhost - Service Worker stopps in Firefox

### ISSUE THREAD

**Issue by radu-cs** [AxaFrance/oidc-client#840]
### Issue and Steps to Reproduce

Clone the react-oidc Demo and start it locally.
Open http://localhost:4200 in Firefox (tested both in stable 103.0.2 and Developer Edition 104.0b10 - 105.0b1).

After logging in and a few successful silent renews the app looses the session because the service worker just stops.

### Versions
react-oidc: 6.3.1
nodejs - 18.7.0
Firefox - 103.0.2
Firefox Developer Edition - 104.0b10
Firefox Developer Edition - 105.0b1
Windows 10 Pro 21H2 - 19044.1889

### Screenshots
![image](https://user-images.githubusercontent.com/33717314/186142574-c1a3725b-1956-493c-9c32-018add830ce0.png)

#### Expected
The silent renew to work as expected.

#### Actual
Because the Service worker is stopped the silent renew is not working.

**Comment by guillaume-chervet** [comment]
hi @radu-cs,

The demo in local work in http instead of https. 
Firefox block cookie tier to from http fto https.

The solution is to update the demo to set up https.

**Comment by radu-cs** [comment]
> hi @radu-cs,
> 
> Thank you for your issue :) The demo in local work in http instead of https. Firefox block cookie tier to from http to https.
> 
> The solution is to update the demo to set up https.
> 
> that why it work here https://black-rock-0dc6b0d03.1.azurestaticapps.net/ and not at http://localhost:4200

Salut Guillaume, :)

Thank you for your answer.
Running the local with HTTPS didn't help much. Eventually the session will fail.
I can confirm that the DEMO running on the provided link works.

The problem is that we really need to work locally while using the react-oidc because the front-end places calls to a back end and needs to pass the Authorization Headers in that call.

Any idea how to achieve that?

**Comment by guillaume-chervet** [comment]
Can you work with another browser for development? or using offline_access scope in order to retrieve refresh token for development purpose?

I think, there are parameters to configure inside mozilla to trust OIDC provider URL.

**Comment by radu-cs** [comment]
> Can you work with another browser for development? or using offline_access scope in order to retrieve refresh token for development purpose?
> 
> I think, there are parameters to configure inside mozilla to trust OIDC provider URL.

Yes we can use a different browser.
I'll try to set up some self signed certificates for https://localhost too and see how it goes.

**Comment by guillaume-chervet** [comment]
Hi have added that cookies exception and then silent signin works on my windows 11 laptop.

![image](https://user-images.githubusercontent.com/52236059/186174871-2af88551-b07b-49a0-b507-af9d5a88a640.png)

**Comment by guillaume-chervet** [comment]
It may be usefull to add a FAQ for that kind of question ^^

**Comment by radu-cs** [comment]
I can confirm that after allowing the exceptions for localhost and the oidc provider everything works as expected. 😄 

Thank you for your quick answer!

**Comment by guillaume-chervet** [comment]
hi @radu-cs , thank you for your issue.
I close the PullRequest. I have added  a FAQ : https://github.com/AxaFrance/oidc-client/blob/main/FAQ.md
