### ISSUE TITLE
postinstall script throws error for pnpm on Windows 11

### ISSUE THREAD

**Issue by noherczeg** [AxaFrance/oidc-client#925]
### Issue and Steps to Reproduce

When I run `pnpm i` in a project where I have the lib added to dependencies it throws an error on Windows 11. With NPM it's okay.

### Versions

6.11.1

### Screenshots

![image](https://user-images.githubusercontent.com/1084847/208795114-a9a35628-ebfe-45f5-ad9b-fdce84dcf51d.png)

**Comment by noherczeg** [comment]
Okay, the problem is with pnpm, because Running `npm i` or `yarn` works fine. Error only comes up for pnpm.

**Comment by guillaume-chervet** [comment]
Hi @noherczeg ,

Thank you very much for your issue, it will help to make this library better.
I didn't know about pnpm.

I will fix it as soon as i can (i'am in holiday)

**Comment by noherczeg** [comment]
> Hi @noherczeg ,
> 
> Thank you very much for your issue, it will help to make this library better.
> I didn't know about pnpm.
> 
> I will fix it as soon as i can (i'am in holiday)

Hi,

No worries, as I mentioned, it seems to be a problem with Windows + IDEA combination only. The postinstall script runs fine with NPM and Yarn as well.

**Comment by noherczeg** [comment]
@guillaume-chervet Can you make the postinstall step optional?

**Comment by guillaume-chervet** [comment]
I pushed this: https://github.com/AxaGuilDEv/react-oidc/commit/4719babcda1f5125e757c8887c22c91f0a898d69

I hope this will work with pnpm

**Comment by guillaume-chervet** [comment]
I will keep itnopzn util it work with pnpm

**Comment by noherczeg** [comment]
I tested this lib with pnpm and Windows 11. Not sure what you meant, but ok :)

**Comment by guillaume-chervet** [comment]
Hi @noherczeg , very sorry for the delay.
We are using now pnpm internally. Now service worker copy is manual and also work with pnpm.
I close the issue but feel free to reopen it if needed.
